- source/Examples/SmartCache/GlobalDispatchTable.h
- source/Examples/SmartCache/Main.cpp
- source/Examples/SmartSharedChannel/GlobalDispatchTable.h
- source/Examples/SmartSharedChannel/Main.cpp
- source/Mlos.Core/ComponentConfig.h
- source/Mlos.Core/Mlos.Core.h
- source/Mlos.Core/MlosPlatform.Std.inl
- source/Mlos.Core/MlosPlatform.h
- source/Mlos.Core/ObjectSerialization.h
- source/Mlos.Core/ObjectSerializationStringView.h
- source/Mlos.Core/PropertyProxy.h
- source/Mlos.Python/mlos/Exceptions.py
- source/Mlos.Python/mlos/Optimizers/RegressionModels/DecisionTreeRegressionModel.py
- source/Mlos.Python/mlos/Optimizers/RegressionModels/HomogeneousRandomForestRegressionModel.py
- source/Mlos.Python/mlos/Optimizers/SimpleBayesianOptimizer.py
- source/Mlos.Python/mlos/Spaces/HypergridAdapters/HypergridAdapter.py
- source/Mlos.Python/mlos/Spaces/Hypergrids.py
- source/Mlos.UnitTest/GlobalDispatchTable.h
- source/Mlos.UnitTest/Main.cpp
- source/Mlos.UnitTest/stdafx.h
Part of a series of ports of internal commits to OSS
> Port ADO changes to GitHub

- website/build_site.sh
- website/nbconvert_template.md.j2
add download button to notebooks
> Notebook download

- README.md
> Adding jupyter launch instructions to README

- source/Mlos.Python/mlos/start_mlos_optimization_runtime.py
- source/Mlos.Python/mlos/start_optimizer_microservice.py
Make scripts output something when they are running.
> make scripts output things when run

- .github/workflows/main.yml
- scripts/dotnet.env
- scripts/run-python-checks.sh
- scripts/run-python-tests.sh
- scripts/util.sh
- source/Mlos.Python/mlos/SynthethicFunctions/PolynomialObjective.py
Add explicit CI pipeline timeouts and reduce some function complexity for a test to address some flaky CI failures #40 
Also adds explicit calling of python3.7 to address environments that have both 3.7 and 3.8 with python3 linking to 3.8
> Fixup pipeline timeouts

- source/Mlos.Notebooks/BayesianOptimization.ipynb
- source/Mlos.Notebooks/SmartCacheOptimization.ipynb
- website/content/menu/index.md
- Added flag `shell=True` for optimizer microservice to run from ipython Notebook
- Modified `current_config: {current_cache_config}` to `current_config: {new_config_values}` for optimization experiment
- Fixed minor typos in Bayesian Optimization Notebook
> Fix subprocess call for optimizer microservice and minor typos

- source/Mlos.Python/mlos/Examples/SmartCache/CacheImplementations/CacheEntry.py
- source/Mlos.Python/mlos/Examples/SmartCache/CacheImplementations/LinkedList.py
- source/Mlos.Python/mlos/Examples/SmartCache/SmartCacheWorkloadLauncher.py
- source/Mlos.Python/mlos/Grpc/BayesianOptimizerFactory.py
- source/Mlos.Python/mlos/Mlos/SDK/MlosExperiment.py
- source/Mlos.Python/mlos/MlosOptimizationServices/ModelsDatabase/ConnectionString.py
- source/Mlos.Python/mlos/Optimizers/OptimizationProblem.py
- source/Mlos.Python/mlos/Optimizers/RegressionModels/Prediction.py
- source/Mlos.Python/mlos/Spaces/Dimensions/CategoricalDimension.py
- source/Mlos.Python/mlos/Spaces/Dimensions/CompositeDimension.py
- source/Mlos.Python/mlos/Spaces/Dimensions/ContinuousDimension.py
- source/Mlos.Python/mlos/Spaces/Dimensions/DiscreteDimension.py
- source/Mlos.Python/mlos/Spaces/Dimensions/EmptyDimension.py
- source/Mlos.Python/mlos/Spaces/Dimensions/SortedBinaryTree.py
- source/Mlos.Python/mlos/Spaces/Point.py
- source/Mlos.Python/mlos/Spaces/unit_tests/TestDimensions.py
Changing `__str__` to `__repr__` and some other slight polish
> More Python docstrings and minor usability improvements for Jupyter

- Makefile
- website/Makefile
Some minor tweaks following #61
> Fixup documentation build scripts

- .github/workflows/main.yml
- Makefile
- scripts/run-python-tests.sh
- source/Mlos.Proto/GeneratePythonGrpcCode.sh
- source/Mlos.Python/mlos/Grpc/__init__.py
A collection of minor python related tweaks while working on #66.
> various python related tweaks

- website/build_site.sh
- website/sphinx/apidoc.sh
- website/test_site_links.sh
> Fix and check for bad anchor links in docs as well

- scripts/dotnet.env
- scripts/init.linux.sh
> add support for zsh

- source/Mlos.Python/mlos/Optimizers/RegressionModels/RegressionEnhancedRandomForestModel.py
- source/Mlos.Python/mlos/Optimizers/RegressionModels/unit_tests/TestRegressionEnhancedRandomForestModel.py
Should fix: test_lasso_hierarchical_categorical_predictions seems flaky #95
> added feature imputation to RERF predict()

- source/Mlos.Python/mlos/Spaces/HypergridAdapters/ContinuousToPolynomialBasisHypergridAdapter.py
- source/Mlos.Python/mlos/Spaces/HypergridAdapters/__init__.py
- source/Mlos.Python/mlos/Spaces/HypergridAdapters/unit_tests/TestContinuousToPolynomialBasisHypergridAdapter.py
Bring SkLearn's PolynomialFeatures transform into MLOS as hypergrid adapter acting on continuous dimensions in the adaptee.
> Add hypergrid adapter exposing SkLearn's PolynomialFeatures for adaptee continuous dimensions

- .github/workflows/nightly.yml
> fixup glob for running long haul tests

- external/ExternalIntegrationExample/ExternalIntegrationExample.cpp
- external/ExternalIntegrationExample/Makefile
- source/Mlos.Core/AnonymousMemoryMlosContext.Linux.cpp
- source/Mlos.Core/FileWatchEvent.Linux.cpp
- source/Mlos.Core/FileWatchEvent.Linux.h
> Cpp Fixups

- .github/workflows/devcontainer.yml
- Makefile
- README.md
- doc/source/index.rst
Updates build status badges for the new github workflows and tweaks some documentation.
> Update build status badges

- .github/workflows/windows.yml
by referencing the right environment variables
> Fix Github Action Caching for Windows

- Makefile
> Enforce minimum code coverage

- .devcontainer/Dockerfile
Revert conda fixups from #287 - upstream fixed their release.
> Revert conda fixups from #287

- mlos_core/mlos_core/optimizers/bayesian_optimizers.py
`pd.DataFrame.to_numpy(config)` == `config.to_numpy()` 😺  mypy doesn't mind
> Shorter version of _df_to_ndarray

- mlos_core/mlos_core/optimizers/bayesian_optimizers.py
- mlos_core/mlos_core/optimizers/optimizer.py
- mlos_core/mlos_core/optimizers/random_optimizer.py
Few small changes to make mypy happy again (I use mypy 1.2.0)
> Add Optional[] annotations to some mlos_core files

- mlos_bench/mlos_bench/service/config_persistence.py
also, add some extra type checks
> make resolve_path parameter handle lists of paths

- conda-envs/mlos_core-3.10.yml
- conda-envs/mlos_core-3.11.yml
- conda-envs/mlos_core-3.8.yml
- conda-envs/mlos_core-3.9.yml
- conda-envs/mlos_core-windows.yml
- conda-envs/mlos_core.yml
- mlos_bench/mlos_bench/launcher.py
- mlos_bench/setup.py
- mlos_core/setup.py
Splitting out some work from #313 and a tweak from #317.
See also #319.
> Rework package dependencies

- mlos_bench/config/optimizers/one_shot_opt.jsonc
- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
- mlos_bench/mlos_bench/optimizers/mock_optimizer.py
- mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
- mlos_bench/mlos_bench/tests/optimizers/mock_opt_test.py
- mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
- mlos_bench/mlos_bench/tunables/tunable.py
- mlos_core/mlos_core/__init__.py
- mlos_core/mlos_core/optimizers/__init__.py
- mlos_core/mlos_core/optimizers/optimizer.py
- mlos_core/mlos_core/spaces/adapters/llamatune.py
This adds support for returning the ConfigSpace defaults as the first config to try.
Splitting some work out from #313.
> Support defaults as first suggestion

- mlos_bench/mlos_bench/environments/base_environment.py
- mlos_bench/mlos_bench/environments/composite_env.py
- mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
- mlos_bench/mlos_bench/services/base_service.py
- mlos_bench/mlos_bench/services/local/local_exec.py
- mlos_bench/mlos_bench/services/remote/azure/azure_services.py
- mlos_bench/mlos_bench/services/types/remote_exec_type.py
- mlos_bench/mlos_bench/services/types/vm_provisioner_type.py
Some circular import cleanup in preparation for config reorgs and importlib based loading from #313
> Circular import cleanup

- Makefile
- doc/source/overview.rst
- mlos_bench/README.md
- mlos_bench/mlos_bench/run.py
- mlos_bench/setup.py
- setup.cfg
Plus a few other small cleanups
- markdown lint from #323
- cleanup forgotten in #320 when splitting that out from #313
> Publish mlos_bench script

- mlos_bench/mlos_bench/tests/conftest.py
- mlos_bench/mlos_bench/tests/environments/mock_env_test.py
- mlos_bench/mlos_bench/tests/optimizers/mock_opt_test.py
- mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py
- mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
- mlos_bench/mlos_bench/tests/storage/exp_load_test.py
- mlos_bench/mlos_bench/tests/storage/trial_config_test.py
- mlos_bench/mlos_bench/tests/tunables/tunable_to_configspace_test.py
- mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
- mlos_bench/mlos_bench/tests/tunables/tunables_str_test.py
Splitting out some smaller work from #313 hacking
> Rework a non-boot param example to a boot param

- mlos_bench/mlos_bench/environments/mock_env.py
- mlos_bench/mlos_bench/tests/tunables/tunable_accessors_test.py
- mlos_bench/mlos_bench/tests/tunables/tunable_comparison_test.py
- mlos_bench/mlos_bench/tests/tunables/tunable_slice_references_test.py
- mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
- mlos_bench/mlos_bench/tests/tunables/tunables_copy_test.py
- mlos_bench/mlos_bench/tunables/tunable.py
Small follow-on to suggestion from #326
> Tunable: rename categorical_value to categorical

- mlos_bench/mlos_bench/tests/config/environments/test_load_environment_config_examples.py
Add tests to make sure that every tunable and covariant group in a child env is in the composite parent env and that they refer to the same objects.
Closes #335
> Additional tunable group merging tests

- mlos_bench/mlos_bench/storage/sql/schema.py
> Explicitly specify size for all varchar fields in the storage

- .devcontainer/build/Dockerfile
Addresses some CI container build issues that popped up from the latest debian base image release in one of our dependencies.
> build fixups for new debian base release

- mlos_bench/mlos_bench/tests/optimizers/conftest.py
- mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py
- mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
Working towards #393. 
SMAC still has some issues - I will work on it and send another PR later.
> Unit tests for mlos_bench + FLAML integration

- mlos_bench/mlos_bench/environments/local/local_env.py
actual scenario in MySQL + SysBench
> Fail the trial if benchmark produces no data

- .github/workflows/codeql.yml
- .github/workflows/devcontainer.yml
- .github/workflows/linux.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/windows.yml
See Also:
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
> Configure Github Actions Merge Queue

- mlos_bench/mlos_bench/environments/composite_env.py
- mlos_bench/mlos_bench/environments/local/local_env.py
- mlos_bench/mlos_bench/environments/mock_env.py
- mlos_bench/mlos_bench/environments/remote/os_env.py
- mlos_bench/mlos_bench/environments/remote/remote_env.py
- mlos_bench/mlos_bench/environments/remote/vm_env.py
- mlos_bench/mlos_bench/environments/status.py
- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
- mlos_bench/mlos_bench/optimizers/mock_optimizer.py
- mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
- mlos_bench/mlos_bench/services/remote/azure/azure_services.py
- mlos_bench/mlos_bench/tests/environments/mock_env_test.py
- mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
- mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
this is consistent with other functions like, e.g., `str.isalpha()`, but, more importantly, allows us to use them applicatively, e.g., `df.score[df.status.apply(Status.is_completed)]`
> Make all `Status.is_*` functions instead of properties.

- .github/workflows/build-dist-test.ps1
- .github/workflows/linux.yml
- .github/workflows/windows.yml
- conda-envs/mlos-3.10.yml
- conda-envs/mlos-3.11.yml
- conda-envs/mlos-3.8.yml
- conda-envs/mlos-3.9.yml
- conda-envs/mlos-windows.yml
- conda-envs/mlos.yml
- mlos_bench/mlos_bench/tunables/tunable.py
Split out and fixup the build and dist-test script for Windows.
> Windows CI and conda numpy version fixups

- .github/workflows/build-dist-test.ps1
- .github/workflows/linux.yml
- conda-envs/mlos-3.11.yml
- conda-envs/mlos-windows.yml
- conda-envs/mlos.yml
- mlos_bench/setup.py
> Enable python 3.11 support

- mlos_bench/mlos_bench/config/schemas/tunables/tunable-params-schema.json
- mlos_bench/mlos_bench/config/schemas/tunables/tunable-values-schema.json
Minor tweak - aids in developing tunable params sets.
> Require non-empty objects for some schemas

- mlos_bench/mlos_bench/environments/base_environment.py
Right now `required_args` applies only to `const_args` and the globals. It is useful to have `const_args` and `tunable_params` interchangeable without updating `required_params` in low-level configs.
> Make required_args apply to both const_args *and* tunables

- mlos_bench/mlos_bench/environments/local/local_env.py
- mlos_bench/mlos_bench/tests/environments/local/__init__.py
- mlos_bench/mlos_bench/tests/environments/local/local_env_telemetry_test.py
- mlos_bench/mlos_bench/tests/environments/local/local_env_test.py
- mlos_bench/mlos_bench/tests/environments/local/local_env_vars_test.py
Mostly, reduce the code duplication
> Fix pylint issues in local_env unit tests

- mlos_bench/mlos_bench/config/schemas/environments/common-environment-subschemas.json
- mlos_bench/mlos_bench/environments/local/local_env.py
- mlos_bench/mlos_bench/environments/remote/remote_env.py
- mlos_bench/mlos_bench/environments/script_env.py
- mlos_bench/mlos_bench/services/remote/azure/azure_services.py
- mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_fileshare_env-full.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/remote_env-full.jsonc
- mlos_bench/mlos_bench/tests/environments/local/local_env_stdout_test.py
- mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
~~**TODO:**~~
**Not** in this PR:
* Extract telemetry from stdout (will do in async mode later)
> Extract benchmark results straight from the local or remote stdout

- .github/workflows/build-dist-test.ps1
- Makefile
- conda-envs/mlos-3.10.yml
- conda-envs/mlos-3.11.yml
- conda-envs/mlos-3.8.yml
- conda-envs/mlos-3.9.yml
- conda-envs/mlos-windows.yml
- conda-envs/mlos.yml
Fixes some uncached rebuild issues that are holding up some other PRs.
> Add some additional conda dependencies to build wheels

- mlos_bench/mlos_bench/storage/__init__.py
- mlos_bench/mlos_bench/storage/base_experiment_data.py
- mlos_bench/mlos_bench/storage/base_storage.py
- mlos_bench/mlos_bench/storage/base_trial_data.py
- mlos_bench/mlos_bench/storage/sql/experiment_data.py
- mlos_bench/mlos_bench/storage/sql/storage.py
- mlos_bench/mlos_bench/storage/sql/trial_data.py
- mlos_bench/mlos_bench/storage/storage_factory.py
Minimal implementation for the demo
> Client-facing storage API

- mlos_bench/mlos_bench/config/schemas/services/local/local-exec-service-subschema.json
- mlos_bench/mlos_bench/services/local/local_exec.py
- mlos_bench/mlos_bench/services/types/local_exec_type.py
- mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/local_exec_service-invalid-abort_on_error.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/local_exec_service-full.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/local_exec_service-partial.jsonc
- mlos_bench/mlos_bench/tests/services/local/local_exec_test.py
- mlos_bench/mlos_bench/tests/services/local/mock/mock_local_exec_service.py
- Future work: add support for remote exec version of this
> Provide configurable ability for locally executed scripts to abort early

- mlos_bench/mlos_bench/storage/base_experiment_data.py
- mlos_bench/mlos_bench/storage/sql/experiment_data.py
- mlos_bench/mlos_bench/storage/sql/storage.py
Small fix to make our ADU demo notebook look nicer
> Fetch additional information about the Experiment (description, etc.)

- mlos_bench/mlos_bench/config/experiments/README.md
- mlos_bench/mlos_bench/config/experiments/experiment_RedisBench.jsonc
- mlos_bench/mlos_bench/launcher.py
- mlos_bench/mlos_bench/run.py
- mlos_bench/mlos_bench/tests/config/environments/test_load_environment_config_examples.py
- mlos_bench/mlos_bench/tests/config/experiments/experiment_test_config.jsonc
> Don't require trial_id in globals config

- .devcontainer/Dockerfile
- .devcontainer/build/build-devcontainer.sh
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/scripts/common/prep-deps-files.sh
- .devcontainer/scripts/run-devcontainer.sh
- .github/workflows/devcontainer.yml
- mlos_bench/setup.py
- reduce devcontainer size (but only a little - see comments below)
- improve cachability
- fixup rebuild times
Closes #550
> devcontainer Fixups

- mlos_bench/mlos_bench/config/schemas/tunables/tunable-params-schema.json
- mlos_bench/mlos_bench/tests/config/schemas/tunable-params/test-cases/good/full/full-tunable-params-test.jsonc
- mlos_bench/mlos_bench/tests/conftest.py
- mlos_bench/mlos_bench/tests/tunables/test_tunable_categoricals.py
- mlos_bench/mlos_bench/tunables/tunable.py
- mlos_bench/mlos_bench/tunables/tunable_groups.py
Closes #450
Just the simple version to start with: convert all categorical inputs to strings.
> Accept non-string categoricals

- mlos_bench/mlos_bench/event_loop_context.py
- mlos_bench/mlos_bench/tests/event_loop_context_test.py
Extracting out from another refactor of SSH support PR #510
> Add asyncio event loop context manager

- mlos_bench/mlos_bench/environments/local/local_env.py
> Attempt to convert results to numeric types

- mlos_bench/mlos_bench/environments/script_env.py
> Do not pass all params as script env variables by default

- .vscode/settings.json
- mlos_bench/mlos_bench/tests/config/environments/remote/test_ssh-tunables.jsonc
- mlos_bench/mlos_bench/tests/config/environments/remote/test_ssh_env.jsonc
- mlos_bench/mlos_bench/tests/environments/remote/test_ssh_env.py
> Tests for shell env var population

- doc/source/index.rst
> Include the links to the coverage images for cross link fixups

- mlos_bench/mlos_bench/config/services/remote/azure/scripts/setup-rg/rg-template.json
Allows deploying a premium fileshare as well.
> More fixups to setup control plane rg arm template

- mlos_bench/mlos_bench/config/environments/apps/fio/fio-post.jsonc
- mlos_bench/mlos_bench/config/environments/apps/fio/fio-pre.jsonc
- mlos_bench/mlos_bench/config/environments/apps/fio/fio.jsonc
Also, fix the shell env variables declarations and rename the output files for readability
Closes #500
> Make FIO benchmark a configurable parameter

- mlos_bench/mlos_bench/config/schemas/config_schemas.py
- mlos_bench/mlos_bench/config/schemas/mlos-bench-config-schema.json
- mlos_bench/mlos_bench/tests/config/schemas/cli/test_cli_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/environments/test_environment_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/globals/test_globals_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/optimizers/test_optimizer_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/services/test_services_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/storage/test_storage_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/tunable-params/test_tunable_params_schemas.py
- mlos_bench/mlos_bench/tests/config/schemas/tunable-values/test_tunable_values_schemas.py
> Single schema definition support

- Makefile
- mlos_bench/README.md
- mlos_bench/mlos_bench/config/experiments/README.md
- mlos_bench/mlos_bench/config/experiments/experiment_RedisBench.jsonc
- mlos_bench/mlos_bench/config/schemas/cli/common-defs-subschemas.json
- mlos_bench/mlos_bench/launcher.py
> experiment_id documentation improvements

- mlos_bench/mlos_bench/config/schemas/cli/cli-schema.json
- mlos_bench/mlos_bench/config/schemas/mlos-bench-config-schema.json
- mlos_bench/mlos_bench/launcher.py
- mlos_bench/mlos_bench/services/types/__init__.py
- mlos_bench/mlos_bench/services/types/config_loader_type.py
- mlos_bench/mlos_bench/tests/config/cli/test-cli-config.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/min-services-items.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/wrong-services-type.jsonc
- mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/good/full/full-cli.jsonc
- mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
> Allow specifying services in CLI args or top level cli config.

- .bumpversion.cfg
- README.md
- doc/source/conf.py
- mlos_bench/README.md
- mlos_bench/_version.py
- mlos_core/README.md
- mlos_core/_version.py
Backreference links to/from pypi
> Readme tweaks

- .github/workflows/devcontainer.yml
> Github Action syntax fixup

- MAINTAINING.md
- README.md
- mlos_bench/README.md
- mlos_bench/mlos_bench/storage/README.md
- mlos_viz/README.md
> README documentation updates

- mlos_bench/mlos_bench/storage/base_storage.py
- mlos_bench/mlos_bench/tests/storage/exp_context_test.py
- mlos_bench/mlos_bench/tests/storage/sql/fixtures.py
Fixups to address discussions in #670
> Fixtures context fixup

- .github/workflows/devcontainer.yml
- .github/workflows/linux.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/windows.yml
See Also: https://docs.opensource.microsoft.com/github/apps/permission-changes/
> Address upcoming changes to default GITHUB_TOKEN permissions

- mlos_bench/mlos_bench/environments/script_env.py
- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/tests/environments/local/local_env_stdout_test.py
Add support for anchored regexes in stdout parsing.
Also improve the details in an error message to make it easier to debug config issues.
> Tweaks for anchored stdout parsing

- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/optimizers/convert_configspace.py
- mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
Also fix some missing conversion issues.
Split out from #690.
> Move config_space to base Optimizer property

- .github/workflows/devcontainer.yml
> Disable flaky logging line in CI workflow

- mlos_bench/mlos_bench/environments/mock_env.py
- mlos_bench/mlos_bench/optimizers/convert_configspace.py
- mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
- mlos_bench/mlos_bench/optimizers/mock_optimizer.py
- mlos_bench/mlos_bench/services/remote/ssh/ssh_service.py
- mlos_bench/mlos_bench/storage/sql/experiment.py
- mlos_bench/mlos_bench/storage/sql/trial.py
- mlos_bench/mlos_bench/tests/storage/trial_telemetry_test.py
- mlos_bench/mlos_bench/tests/util_nullable_test.py
- mlos_bench/mlos_bench/tunables/tunable.py
- mlos_bench/mlos_bench/util.py
basically, a poor man's Maybe monad
> A function for a popular `None if value is None else func(value)` code pattern

- mlos_bench/mlos_bench/storage/sql/__init__.py
- mlos_bench/mlos_bench/tests/config/schemas/storage/test_storage_schemas.py
Adds some additional checks for consistency with other schema tests.
> Tweak Storage schema related tests

- mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
- mlos_core/mlos_core/optimizers/flaml_optimizer.py
another PR to reduce the size of #730
> Fix docstrings for mlos_core SMAC and FLAML optimizers

- mlos_viz/setup.py
https://github.com/dabl/dabl/pull/341
> Pin a lower version of matplotlib while we wait for dabl to get fixed

- mlos_core/setup.py
See Also: https://github.com/numpy/numpy/issues/26710
> Temporarily avoid broken numpy dependency

- mlos_bench/mlos_bench/os_environ.py
There is a linting issue for the os specific variables
This should fix it
> Fix Linting Error in os_environ.py

- .bumpversion.cfg
- Makefile
- doc/source/version.py
- mlos_bench/mlos_bench/version.py
- mlos_core/mlos_core/version.py
- mlos_viz/mlos_viz/version.py
Especially for build system updates.
> Bump version: 0.5.1 → 0.6.0

- Makefile
Splitting out from #802 to benefit other jobs as well.
> make doc CI fixups

- mlos_bench/mlos_bench/__init__.py
- mlos_core/mlos_core/__init__.py
- mlos_viz/mlos_viz/__init__.py
Minor tweaks to provide common attributes like 
```python
mlos_core.__version__
mlos_core.VERSION
```
> Version identifier packaging tweaks

- .bumpversion.cfg
- doc/source/version.py
- mlos_bench/mlos_bench/version.py
- mlos_core/mlos_core/version.py
- mlos_viz/mlos_viz/version.py
Bump version after #844 which represents a breaking config schema change.
> Bump version: 0.6.0 → 0.6.1

- mlos_bench/mlos_bench/config/schemas/optimizers/mlos_core-optimizer-subschema.json
- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
- mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
- mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
- mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
- mlos_bench/mlos_bench/tests/optimizers/conftest.py
- mlos_bench/mlos_bench/tests/optimizers/grid_search_optimizer_test.py
See Also: https://github.com/microsoft/MLOS/pull/713
> Finish converting max_iterations to max_suggestions

- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/storage/base_experiment_data.py
- mlos_bench/mlos_bench/util.py
Include `strtobool` from a now deprecated version of python.
---
- Closes #865 
---
- 🛠️ Bug fix
---
> Include strtobool from older version of python

- .devcontainer/scripts/README.md
Updates some documentation on the `acr purge` task used to keep storage retention reasonable for devcontainer images.
---
> Update container purge docs

- README.md
Adds a set of publication links to the front page readme.
---
---
> Add publication links

- mlos_bench/mlos_bench/optimizers/convert_configspace.py
- mlos_bench/mlos_bench/tests/dict_templater_test.py
- mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
- mlos_viz/mlos_viz/base.py
Apply some minor linter complaint fixes.
---
Splitting out some unrelated new linter complaints from #852 
---
- 🛠️ Bug fix
---
> Apply some minor linter complaint fixes

- mlos_bench/mlos_bench/tests/launcher_in_process_test.py
- setup.cfg
Ignores some warnings in the pytest output that come from dependencies.
---
Purely cosmetic to make it easier to see real errors.
---
- 🧪 Tests
---
> Ignore some pytest warnings

- Makefile
- conda-envs/mlos.yml
- doc/copy-source-tree-docs.sh
- doc/source/conf.py
- mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
- mlos_bench/mlos_bench/util.py
- mlos_bench/pyproject.toml
- mlos_core/mlos_core/tests/spaces/spaces_test.py
- mlos_core/pyproject.toml
- mlos_viz/pyproject.toml
Small tweaks
---
- pylint dependency mixup
- mypy fixup
- Minor perf improvement on Makefile file enumeration.
- Add typevar hints for `nullable` return type.
- Fix a minor build system issue
- List python 3.13 as one of the supported versions (#879)
---
- 🛠️ Bug fix
- 🔄 Refactor
---
Usual pytest and mypy CI checks for `nullable`
---
Split out from #720 
---
> Small tweaks

- Makefile
- conda-envs/mlos-3.10.yml
- conda-envs/mlos-3.11.yml
- conda-envs/mlos-3.12.yml
- conda-envs/mlos-3.13.yml
- conda-envs/mlos-windows.yml
- conda-envs/mlos.yml
Remove use of yq.
---
Removes the use of yq which doesn't always exist and running it via conda apparently has issues.
---
- 🛠️ Bug fix
---
CI
---
Fixes a bug introduced in #904 
---
> Remove use of yq

- mlos_bench/mlos_bench/storage/sql/alembic/script.py.mako
Minor adjustments to the template introduced in #906
> Minor tweaks to the revision script template to avoid some future linting fixups

- .bumpversion.cfg
- Makefile
- doc/source/version.py
- mlos_bench/mlos_bench/version.py
- mlos_core/mlos_core/version.py
- mlos_viz/mlos_viz/version.py
> New release 0.6.2

- .pre-commit-config.yaml
- .vscode/settings.json
- mlos_bench/mlos_bench/environments/base_environment.py
- mlos_bench/mlos_bench/environments/local/local_fileshare_env.py
- mlos_bench/mlos_bench/optimizers/base_optimizer.py
- mlos_bench/mlos_bench/schedulers/base_scheduler.py
- mlos_bench/mlos_bench/services/base_service.py
- mlos_bench/mlos_bench/services/config_persistence.py
- mlos_bench/mlos_bench/storage/base_storage.py
- mlos_bench/mlos_bench/tests/conftest.py
- mlos_bench/mlos_bench/tests/services/remote/ssh/fixtures.py
- mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_fileshare.py
- mlos_bench/mlos_bench/tests/storage/sql/fixtures.py
- mlos_bench/mlos_bench/tunables/tunable_groups.py
- mlos_core/mlos_core/tests/spaces/monkey_patch_quantization_test.py
- pyproject.toml
- setup.cfg
Type hint fixups
---
A few type hint fixups.
---
- 🔄 Refactor
---
- CI
- Local
---
After #916 
---
> Type hint fixups

- mlos_bench/mlos_bench/schedulers/base_scheduler.py
Make Schedule properties private
---
Mostly cosmetic change being split out from #720 
---
- 🔄 Refactor
---
> Make Scheduler properties private

- mlos_bench/mlos_bench/services/types/config_loader_type.py
Export additional methods from the SupportsConfigLoading type
---
Exposes to pre-existing methods for the Protocol type.
---
- 🔄 Refactor
---
Small change split out from #720 
---
> Export additional methods from the SupportsConfigLoading type

- .github/pull_request_template.md
- .pre-commit-config.yaml
- CONTRIBUTING.md
- MAINTAINING.md
- README.md
- SECURITY.md
- doc/README.md
- mlos_bench/README.md
- mlos_bench/mlos_bench/config/services/remote/azure/scripts/setup-rg/README.md
- mlos_bench/mlos_bench/environments/README.md
- mlos_bench/mlos_bench/services/README.md
- mlos_bench/mlos_bench/services/remote/azure/README.md
- mlos_bench/mlos_bench/storage/README.md
- mlos_bench/mlos_bench/storage/sql/alembic/README.md
- mlos_bench/mlos_bench/tests/services/remote/ssh/README.md
- mlos_core/README.md
- mlos_core/mlos_core/spaces/adapters/README.md
Enable and apply mdformat pre-commit rules
---
- 🔄 Refactor
---
> mdformat pre-commit rules

- doc/requirements.txt
- doc/source/conf.py
Allow sphinx resolution of Azure types again.
See Also:
- https://github.com/Quansight-Labs/intersphinx_registry/pull/58
- #912 
- 🛠️ Bug fix
> Allow sphinx resolution of Azure types again.

- .github/workflows/linux.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- SECURITY.md
- conda-envs/mlos-3.10.yml
- conda-envs/mlos-3.11.yml
- conda-envs/mlos-3.12.yml
- conda-envs/mlos-3.13.yml
- conda-envs/mlos-windows.yml
- conda-envs/mlos.yml
- mlos_bench/mlos_bench/services/config_persistence.py
- mlos_bench/mlos_bench/storage/sql/alembic/versions/8928a401115b_adding_experiment_table_columns_to_.py
- mlos_core/mlos_core/spaces/adapters/README.md
pre-commit updates
- hook version updates
- add badge
> pre-commit updates

- README.md
- mlos_bench/mlos_bench/config/README.md
Minor doc tweaks
Minor doc tweaks
> Minor doc tweaks

- mlos_core/mlos_core/data_classes.py
mypy linting fixup
mypy linting fixup
- 🛠️ Bug fix
Unit tests and lints checks.
Can be merged before any of the other refactor series.
> mypy linting fixup
