.github/workflows/main.yml

I'm still seeing a few timeout failures on the unit tests.
This is a quick change to simply increase the timeout for now.

Increase python unit test CI timeout

---

README.md
documentation/01-Prerequisites.md
scripts/parse-pip-requirements-from-environment-yaml.py
source/Mlos.Notebooks/environment.yml

cc @bpkroth @markusweimer 
Not sure if I'm undoing some of the work @markusweimer has been doing here before.
I grouped the OS independent steps in the beginning.
I think the "manual python" version is not that useful because it's ubuntu only (not sure if the ppas work for debian?), and there's really no reason to compile your own version of pyodbc, so I removed it.

reorganize and update conda/python install docs

---

website/build_site.sh

Currently if you click on the "notebooks section" link on the main README.md (or it's derivative in github pages) you'll wind up at https://microsoft.github.io/MLOS/notebooks/ which is a blank page.
This adds the links to the body of that page that also already appear on the sidebar.

Provide some links to the notebooks in the docs pages

---

.github/workflows/main.yml
.vscode/launch.json
.vscode/settings.json
CMakeLists.txt
build.cake
build/CMakeHelpers/CheckForMlosSharedMemories.sh
build/CMakeHelpers/RemoveMlosSharedMemories.sh
build/CMakeHelpers/RunTestsAndSharedMemChecks.sh
build/DotnetWrapperRules.mk
build/Mlos.Common.cmake
build/Mlos.Cpp.UnitTest.cmake
build/Mlos.Cpp.cmake
build/Mlos.NetCore.cmake
scripts/util.sh
source/Examples/SmartCache/CMakeLists.txt
source/Mlos.Agent.Server/MlosAgentServer.cs
source/Mlos.Agent.Server/TargetProcessManager.cs
source/Mlos.Agent/MainAgent.cs
source/Mlos.Core/MlosContext.cpp
source/Mlos.Core/SharedConfigManager.cpp
source/Mlos.Model.Services.UnitTests/UnitTests.cs
source/Mlos.NetCore.UnitTest/CMakeLists.txt
source/Mlos.NetCore.UnitTest/DummyTests.cs
source/Mlos.NetCore.UnitTest/Mlos.NetCore.UnitTest.csproj
source/Mlos.UnitTest/CMakeLists.txt

This is initial work to get C++ UnitTests (Mlos.UnitTest and SmartCache) working in Linux CI.
Main other issues it addresses:
- Provide a mechanism for Linux to discover where to find the SettingsRegistry assemblies for the Mlos.Agent to load
- DEBUG compile definition for MSVC compatibility
- Skip (and comment) some failing unit tests on the dotnet side
There are some known issues with it, that @grlap and I discussed addressing in future PR:
- print statements are not configurable, so while the output may be helpful in an interactive development environment, they aren't suitable for a service/daemon environment
- there are some security concerns for loading settings registry DLLs are runtime
- one solution there is to give the agent a config mechanism (file or args) to be able to choose …

Work to get C++ unit tests working in Linux CI

---

.vscode/launch.json
documentation/01-Prerequisites.md
source/Mlos.Agent.Server/CliOptionsParser.cs
source/Mlos.Agent.Server/Mlos.Agent.Server.csproj
source/Mlos.Agent.Server/MlosAgentServer.cs

Cli parser fixups

---

.editorconfig
.vscode/settings.json

Tweaks to vscode plugins to reflow comments at a width that matches the rest of the code style.
Noticed by @grlap

Fixup comment word wrap settings for vscode vim

---

source/Examples/SmartCache/Main.cpp
source/Examples/SmartSharedChannel/Main.cpp
source/Mlos.Core/Mlos.Core.h
source/Mlos.UnitTest/Main.cpp

Recently we discovered the following error in CI for Linux builds:
```txt
Scanning dependencies of target Mlos.Core
make[3]: Leaving directory '/home/runner/work/MLOS/MLOS/out/cmake/Debug'
make[3]: Entering directory '/home/runner/work/MLOS/MLOS/out/cmake/Debug'
[ 20%] Building CXX object source/Mlos.Core/CMakeFiles/Mlos.Core.dir/ArenaAllocator.cpp.o
In file included from /home/runner/work/MLOS/MLOS/source/Mlos.Core/ArenaAllocator.cpp:16:
In file included from /home/runner/work/MLOS/MLOS/source/Mlos.Core/Mlos.Core.h:90:
In file included from /home/runner/work/MLOS/MLOS/source/Mlos.Core/PropertyProxy.h:18:
In file included from /home/runner/work/MLOS/MLOS/source/Mlos.Core/ObjectSerialization.h:19:
/home/runner/work/MLOS/MLOS/source/Mlos.Core/StringTypes.h:89:38: error: use of undeclared …
```

Fixups for libstdc++-10 support

---

.github/workflows/main.yml
build.cake

- run build.cake for the right config
- run cmake in parallel inside cake
- run/test the cmake-install target

some build pipeline tweaks

---

.github/workflows/nightly.yml

previously we only set the overall job timeout beyond the default of 360 minutes
(6 hours)
with this change we also explicitly set the timeout for the longhaul execution
step in the job (in case that was also defaulting to 360)
still not sure if this will fix things, but worth a try
closes #113

increase longhaul job step timeout beyond default

---

source/Mlos.Python/mlos/Optimizers/unit_tests/TestBayesianOptimizer.py
source/Mlos.Python/mlos/Spaces/Point.py
source/Mlos.Python/mlos/Spaces/unit_tests/TestHierarchicalHypergrid2.py

Implementing __getstate__ and __setstate__ on Point makes all instances of Point serializable and by extension the entire optimizer.

Made Opitimizer Serializable

---

source/Mlos.Python/mlos/Optimizers/RegressionModels/RegressionEnhancedRandomForestModel.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/RegressionModel.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/SklearnLassoRegressionModelConfig.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/SklearnRandomForestRegressionModelConfig.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/SklearnRidgeRegressionModelConfig.py

RegressionModelConfig was a mistake. It's now gone. 
Remaining work: Remove DefaultConfigMeta #145 altogether also. I didn't want to do it now because I don't want to mess with RERF code too much, as Ed is editing it too.

Removed RegressionModelConfig class

---

source/Mlos.Python/mlos/Optimizers/RegressionModels/HomogeneousRandomForestRegressionModel.py
source/Mlos.Python/mlos/Optimizers/unit_tests/TestBayesianOptimizer.py

samples_fraction_per_estimator is a parameter that governs what fraction of the original dataset is used to train each tree in the HomogeneousRandomForestRegressionModel. 
The desired behavior is to have `min(samples_fraction_per_estimator * num_samples, num_valid_samples)` however the way this was coded up until now was: `samples_fraction_per_estimator * num_valid_samples`.
This PR rectifies that.
Edit: also fixed a bug in TestBayesianOptimizer.

Fixed how we compute the number of samples per tree

---

source/Mlos.Python/mlos/Optimizers/BayesianOptimizerConfigStore.py
source/Mlos.Python/mlos/Optimizers/BayesianOptimizerConvergenceState.py
source/Mlos.Python/mlos/Optimizers/ExperimentDesigner/ExperimentDesigner.py
source/Mlos.Python/mlos/Optimizers/ExperimentDesigner/UtilityFunctionOptimizers/GlowWormSwarmOptimizer.py
source/Mlos.Python/mlos/Optimizers/ExperimentDesigner/UtilityFunctionOptimizers/RandomSearchOptimizer.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/DecisionTreeConfigStore.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/HomogeneousRandomForestConfigStore.py

Most changes here were informed by repeatedly running the optimizer- I estimate that within the last month it completed somewhere between 10,000 and 30,000 complete optimization runs against synthetic functions including:
- polynomial objective: 2D, degree 2, various domain sizes, various coefficient of variations
- nested polynomial objective: 5 2D, 2nd degree polynomials for a total of 11 parameters (one of which was categorical)
- multilevel quadratic
Each time, the optimizer was run with a different configuration (many of which were chosen at random). What became apparent is that many of the parameters exposed by the optimizer have ranges that are too wide and either turn the entire process into random search (e.g.: min_samples_to_fit = 100000), or make it prohibitively expensive …

Adjusted parameter ranges for many of the Optimizer's components.

---

source/Mlos.Python/mlos/Logger.py
source/Mlos.Python/mlos/Tracer.py

Really small features that I've had to add to Tracer and to Logger. Basically, when after each optimization run, I want to have an EvaluationReport that contains the tracer events, and all the log records (along with goodness of fit metrics over time etc.). I also want to be able to pickle/unpickle them and to dump them to files. 
Furthermore, the evaluation uses multiprocessing, so capturing the PID in the Traces helps disambiguate events from different runs and render them pretty.
Tracer:
* we capture thread id and PID with traced events
Logger:
* we save the record as is, instead of turning it into a dictionary. This is a minor perf improvement, but it also allows us to use the formatter specified by the user when dumping records to file.
* we can dump traces to file now.

Small feature additions to tracer and to logger

---

source/Mlos.Python/mlos/Optimizers/OptimizerBase.py
source/Mlos.Python/mlos/Optimizers/unit_tests/TestBayesianOptimizer.py

Basically, the absence of parentheses in this expression: 
`predictions_df[dof_column_name].notna() & (predictions_df[dof_column_name] != 0)`
Messed up the order of operations, which resulted in classifying essentially random rows as containing nulls or having insufficient degrees of freedom. Occasionally, a row containing an optimum would be removed and that's when our assert fired.
We need more asserts.

Fixed a bug that caused intermitted test failures

---

build/Mlos.Cpp.UnitTest.cmake

Minor issue I noticed while working on debugging help for #60.
When run through the cmake unit tests on an otherwise clean environment, we pip install mlos without marking it editable.  This makes live debugging confusing since the edits don't seem to take effect when re-running the microservice.

use "editable" mode when pip installing mlos for unit test pipelines

---

source/Mlos.Python/mlos/Optimizers/BayesianOptimizer.py
source/Mlos.Python/mlos/Optimizers/unit_tests/TestBayesianOptimizer.py

This PR is a first step towards multi-objective optimization.
It's really simple: the user can now define an objective space that's multi-dimensional. Subsequently the user can register observations that contain values for one or more of those objectives. 
Still, only one objective is optimized. Effectively, all those extra objectives are remembered, but ignored.

Registering multiple objectives

---

.github/workflows/main.yml
build.linux.sh
build/Common.mk
build/Mlos.Cpp.cmake
source/Examples/SmartCache/Main.cpp
source/Examples/SmartSharedChannel/Main.cpp
source/Mlos.Core/Mlos.Core.h
source/Mlos.Core/ObjectDeserializationCallback.h
source/Mlos.SettingsSystem.CodeGen/CodeWriters/CppObjectExchangeCodeWriters/CppObjectDeserializeHandlerCodeWriter.cs
source/Mlos.SettingsSystem.CodeGen/CodeWriters/CppObjectExchangeCodeWriters/CppObjectDeserializeRuntimeCallbackCodeWriter.cs
source/Mlos.SettingsSystem.CodeGen/CodeWriters/CppObjectExchangeCodeWriters/CppObjectGetVariableDataSizeCodeWriter.cs
source/Mlos.SettingsSystem.CodeGen/CodeWriters/CppObjectExchangeCodeWriters/CppObjectSerializationVariableDataCodeWriter.cs
source/Mlos.SettingsSystem.CodeGen/CodeWriters/CppObjectExchangeCodeWriters/CppProxyVerifyVariableDataCodeWriter.cs
source/Mlos.SettingsSystem.CodeGen/CodeWriters/CppObjectExchangeCodeWriters/CppTypeReflectionTableCodeWriter.cs
source/Mlos.UnitTest/Main.cpp
source/Mlos.UnitTest/SharedChannelTests.cpp

Initial work to enable gcc support #23 
Started as a hack to workaround cmake's FetchContent not appearing to pass the CMAKE_COMPILER_ID through when building with CXX=clang++-10
This also fixes a few minor issues that gcc complained about.

Initial work to add gcc support

---

build/Mlos.Cpp.UnitTest.targets
source/Examples/SmartCache/SmartCache.vcxproj
source/Examples/SmartSharedChannel/SmartSharedChannel.vcxproj
source/Mlos.UnitTest/Mlos.UnitTest.vcxproj

Github bumped the version of msbuild tools on Windows runners for our Github Action CI pipeline:
https://github.com/actions/virtual-environments/commit/9a16e36b2847d6e56ba0ff3c0bd275674f1988cc#diff-816219d3c9f30fcc1c40f88ca826c1662bf99eded781c1b419dd2dfb577ae227L216
This exposed a few build authoring issues we had on Windows.  This PR should fix those.

Windows build fixups for recent MSBuild tool versions

---

Makefile
scripts/install.cmake.sh

At the moment the cmake apt repo we rely on has published newer cmake packages that specify a dependency that doesn't exist.  This breaks a clean cmake install (as we do during docker image build).
For the moment, we're adding that version to a rejectlist to workaround the issue.

Avoid some broken cmake package versions in Docker image build

---

source/Mlos.Python/mlos/Spaces/unit_tests/TestSortedBinaryTree.py

Fixes #178.
It's unclear to me whether unittest ran these. But they pass ;)

rename test class to start with Test so pytest finds them

---

source/Mlos.Python/mlos/Optimizers/unit_tests/TestBayesianOptimizer.py

cc @bpkroth @byte-sculptor current tests rely too much on randomness, we can
a) change the thresholds (this PR)
b) run the optimizer for more iterations (how many? takes longer)
c) fix random seeds
I think this is the easiest fix to keep it somewhat meaningful and fast and not have master failing a lot.

be more loosy-goosy with the test thresholds for less flaky tests

---

.github/workflows/main.yml

Should fix this error that recently showed up in our docker/build-push-action step:
"Error: Invalid Opening Quote: a quote is found inside a field at line 2"

Remove quotes from a docker label

---

.github/workflows/main.yml
build.cake

- Increase the timeouts on the pytest runs.
There have been some timeouts recently, due in part to the addition of code
coverage tracking (#187).
- Separate the pylint checks (short) from the pytest runs (long, flaky) so that
we can have the docker image publish task proceed in nightly runs even if the
pytest run was flaky.

Tweaks to Python Test CI pipelines

---

.github/workflows/main.yml

Attempting to fix the following error:
```
->  Pinging Codecov
https://codecov.io/upload/v4?package=github-action-20201130-cc6d3fe&token=secret&branch=main&commit=27c39e71a07b063cc2c59a3eb72609a722d17510&build=397032896&build_url=http%3A%2F%2Fgithub.com%2Fmicrosoft%2FMLOS%2Factions%2Fruns%2F397032896&name=&tag=&slug=microsoft%2FMLOS&service=github-actions&flags=unittests&pr=&job=&cmd_args=Q,f,n,F,Z
HTTP 400
ERROR: Tokenless uploads are only supported for public repositories on GitHub Actions that can be verified through the Actions API.
Please use an upload token if your repository is private and specify it via the -t flag. You can find the token for this repository
at the url below on codecov.io (login required):
Repo token: https://codecov.io/gh/microsoft/MLOS/settings
Documentation: …
```

Use explicit codecov token to upload results

---

.github/workflows/main.yml

Avoids the following error:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.9.0/x64/bin/licenseheaders", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/licenseheaders.py", line 612, in main
arguments = parse_command_line(sys.argv)
File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/licenseheaders.py", line 304, in parse_command_line
known_extensions = [ftype+":"+",".join(conf["extensions"]) for ftype, conf in typeSettings.items()]
File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/licenseheaders.py", line 304, in <listcomp>
known_extensions = [ftype+":"+",".join(conf["extensions"]) for ftype, conf in typeSettings.items()]
KeyError: 'extensions'
Error: Process …
```

Avoid broken licenseheaders package version

---

source/Mlos.Python/mlos/Spaces/Point.py
website/sphinx/apidoc.sh

With sphinx 3.4.0-3.4.2 (released in late December 2020), sphinx generates
asserts by the Point module due to invalid keys (e.g. `__sphinx_mock__`) in the Point.
```txt
Exception occurred:
File "/src/MLOS/source/Mlos.Python/mlos/Spaces/Point.py", line 75, in __getitem__
raise KeyError(f"This Point does not have a value along dimension: {dimension_name}")
KeyError: 'This Point does not have a value along dimension: __sphinx_mock__'
```
Fixes #210 (at least enough that we can submit PRs and run the nightly CI jobs again)

Workaround an issue uncovered by recent versions of sphinx

---

.github/workflows/main.yml

Our nightly CI jobs have been failing to push updated docker images recently.
We, along with lots of others, are experiencing an [`unknown blob` error issue](https://github.community/t/random-unknown-blob-error-when-pushing-to-docker-github-package-repository/16725/7) when pushing to the old docker.pkg.github.com package registry.
This registry was superseded by the ghcr.io Github Container Registry service:
https://github.blog/2020-09-01-introducing-github-container-registry/
We aren't using it anymore, so this changeset disables the use of the older registry to get the pipelines publishing to ghcr.io once again.

Disable old docker package registry

---

source/Mlos.Python/mlos/OptimizerEvaluationTools/ObjectiveFunctionBase.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/OptimizerEvaluationReport.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/OptimizerEvaluator.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/OptimizerEvaluatorConfigStore.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/SyntheticFunctions/PolynomialObjectiveWrapper.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/unit_tests/TestOptimizerEvaluator.py
source/Mlos.Python/mlos/Optimizers/OptimizationProblem.py
source/Mlos.Python/mlos/Optimizers/ParetoFrontier.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/RegressionModelFitState.py

OptimizerEvaluator now tracks pareto over time, pareto volume over time and multi-objective goodness of fit metrics.
I also added a read_from_disk() method to OptimizerEvaluationReport to mirror the write_to_disk() method and updated the tests to make use of it.

Adding Multi-Objective Optimization to Optimizer Evaluator

---

source/Mlos.Python/mlos/OptimizerEvaluationTools/ObjectiveFunctionConfigStore.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/ObjectiveFunctionFactory.py

This PR makes it possible to create the new objective function via the ObjectiveFunctionFactory.
Existing tests cover this addition.

Added Enveloped Waves to the ObjectiveFunctionFactory

---

source/Mlos.Python/mlos/OptimizerEvaluationTools/OptimizerEvaluationReport.py
source/Mlos.Python/mlos/OptimizerEvaluationTools/OptimizerEvaluator.py

This really simple change adds a start time and an end time to the optimizer evaluation report, thus allowing us to also know how long the optimization process took.

Adding start and end timestamps to the evaluation report

---

source/Mlos.Python/mlos/Optimizers/ExperimentDesigner/UtilityFunctionOptimizers/GlowWormSwarmOptimizer.py
source/Mlos.Python/mlos/Optimizers/ExperimentDesigner/UtilityFunctionOptimizers/RandomSearchOptimizer.py
source/Mlos.Python/mlos/Optimizers/ExperimentDesigner/UtilityFunctionOptimizers/unit_tests/TestUtilityFunctionOptimizers.py

I was working on Random Near Incumbent Optimizer and I noticed that GlowWormSwarmOptimizer was doing something really wrong with the context features. I don't really understand how/if it ever worked with context.
So this is a quick fix, where we have the worms keep track of the parameter values (not feature values) and only constructing the features dataframe when calling the utility function. This way, the glow worm swarm optimizer can suggest optimal parameters for a given context, instead of suggesting optimal parameters and context. I really don't know how it ever worked. I suspect it was never able to compute the utility value, and always bailed on the first 'if' producing a de-facto random suggestion.

Making glow worm optimizer use the context

---

source/Mlos.Python/mlos/Optimizers/RegressionModels/RegressionEnhancedRandomForestModel.py
source/Mlos.Python/mlos/Optimizers/RegressionModels/unit_tests/TestRegressionEnhancedRandomForestModel.py
source/Mlos.Python/mlos/Spaces/HypergridAdapters/CategoricalToOneHotEncodedHypergridAdapter.py
source/Mlos.Python/mlos/Spaces/HypergridAdapters/ContinuousToPolynomialBasisHypergridAdapter.py
source/Mlos.Python/mlos/Spaces/HypergridAdapters/unit_tests/TestCategoricalToOneHotEncodedHypergridAdapter.py
source/Mlos.Python/mlos/Spaces/HypergridAdapters/unit_tests/TestContinuousToPolynomialBasisHypergridAdapter.py

The initial RERF rewrite using the (then new) hypergrid adapters `CategoricalToOneHotEncodedHypergridAdapter` and `ContinuousToPolynomialBasisHypergridAdapter` incorrectly performed the transform operations.  This PR corrects this mistake in the RERF `.transform_x()` method.
Also:
1. Added new unit tests for stacking `CategoricalToOneHotEncodedHypergridAdapter` and `ContinuousToPolynomialBasisHypergridAdapter`.
2. Parameterized unit tests in `CategoricalToOneHotEncodedHypergridAdapter` to simplify code.
3. Added comment to  `CategoricalToOneHotEncodedHypergridAdapter` explaining why the `CategoricalToDiscreteHypergridAdapter` is used.

Cleaned up stacking polynomial features adapter on one hot encoding adapter

---

.bumpversion.cfg
.devcontainer/Dockerfile
.devcontainer/scripts/common/prep-deps-files.sh
.devcontainer/scripts/prep-container-build
.devcontainer/scripts/prep-container-build.ps1
Makefile
README.md
codecov.yml
conda-envs/mlos_core-3.10.yml
conda-envs/mlos_core-3.11.yml
conda-envs/mlos_core-3.8.yml
conda-envs/mlos_core-3.9.yml
conda-envs/mlos_core-windows.yml
conda-envs/mlos_core.yml
doc/source/conf.py
doc/source/installation.rst
mlos_bench/_version.py
mlos_bench/setup.py
mlos_core/_version.py
mlos_core/setup.py
scripts/update-version.sh
setup.cfg

- Switch from our manual script to bumpversion for managing manual tags/version changes related to releases.
- Bumps the version to 0.1.0
Note: Since this is a PR that gets squashed, will have to adjust the tag that points to v0.1.0 after merging
- Adds a programmatic method for adding semver versioning based off of that.
Mostly useful for local builds.

Automatic versioning support

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/extensions.json

Attempts to workaround some upstream release version mismatch issues for now so we can build the devcontainer in the pipelines.
See Also: <https://github.com/conda/conda-libmamba-solver/issues/169#issuecomment-1490509810>

Workaround upstream conda release issue

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/scripts/README.md
Makefile
doc/Dockerfile
doc/nginx-default.conf
doc/nginx-docker.sh
mlos_bench/db/osat.sql

Windows (or other platforms) may listen on port 80 and cause conflicts when WSL2 tries to forward ports for both sides so that `localhost` resolution behaves as expected despite the VM technically being a separate host.
When this happens the devcontainer can fail to start due to in ability for nginx docs container to listen on port 80.
To workaround this we simply tell it to listen on port 81 instead.  The devcontainer forwards the port to a different one on the host anyways.
Additionally, we document some commands for cleaning up stale container images in the ACR service to avoid excessive storage usage.

Devcontainer port conflict tweaks

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/scripts/prep-container-build
.devcontainer/scripts/prep-container-build.ps1
Makefile
doc/Dockerfile
doc/nginx-default.conf
doc/nginx-docker.sh

WSL2 has some weird port mapping behavior that automatically puts container listening ports into the host's network ports as well, leading to port clashes when we run multiple devcontainers at once.
To work around this we make use of nginx container's ability to listen on dynamic ports and docker compose ability to publish container ports to random other host ports.
To make this work we write a small `.env` file in the `.devcontainer/` directory that docker compose automatically picks up during the nginx container build process.
Additionally, we stop pulling upstream container images on each vscode launch for now.
See Also: https://github.com/microsoft/vscode-remote-release/issues/8179

devcontainer nginx port fixups

---

.cspell.json
mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/environments/local/local_env.py
mlos_bench/mlos_bench/environments/mock_env.py
mlos_bench/mlos_bench/optimizers/convert_configspace.py
mlos_bench/mlos_bench/optimizers/mock_optimizer.py
mlos_bench/mlos_bench/tests/conftest.py
mlos_bench/mlos_bench/tests/tunables/tunable_accessors_test.py
mlos_bench/mlos_bench/tests/tunables/tunable_comparison_test.py
mlos_bench/mlos_bench/tests/tunables/tunable_definition_test.py
mlos_bench/mlos_bench/tests/tunables/tunable_group_indexing_test.py
mlos_bench/mlos_bench/tests/tunables/tunable_to_configspace_test.py
mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
mlos_bench/mlos_bench/tests/tunables/tunables_copy_test.py
mlos_bench/mlos_bench/tunables/covariant_group.py
mlos_bench/mlos_bench/tunables/tunable.py
mlos_bench/mlos_bench/tunables/tunable_groups.py

More work being split out from #313 
- Handle `null` (in json, `None` in python) values for categoricals.
- Disallow duplicate values in categoricals.
- Provide type aware setters (compromise to a much much larger type aware rework for `Tunables` that isn't super beneficial).
- Slight method renaming for clarity.
- For convenience, allow accessing the `TunableGroups` by `Tunable`, not just it's name.
- Add `__contains__` method to `TunableGroups` so we can do `if tunable in tunable_group` checks
- Add a few more tests for `Tunable`, `TunableGroups`, and `CovariantTunableGroup` definitions.
Coverage should be about 90% overall now, and 99+% on those files.

Tweaks to Tunables

---

mlos_bench/mlos_bench/environments/local/local_env.py
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/tests/config/__init__.py
mlos_bench/mlos_bench/tests/config/environments/test_load_environment_config_examples.py
mlos_bench/mlos_bench/tests/config/optimizers/test_load_optimizer_config_examples.py
mlos_bench/mlos_bench/tests/config/services/test_load_service_config_examples.py
mlos_bench/mlos_bench/tests/config/storage/test_load_storage_config_examples.py
mlos_bench/mlos_bench/tests/launcher_test.py
mlos_bench/mlos_bench/tests/services/local/local_exec_python_test.py
mlos_bench/mlos_bench/tests/services/local/local_exec_test.py
mlos_bench/mlos_bench/util.py

We have various places that need to use `.replace("\\", "/")` after `os.path.join(...)` to canonicalize the paths across platforms.
This consolidates that into a single function.

Path join tweak

---

mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py
mlos_bench/mlos_bench/tunables/tunable.py

That bugfix allows us to resume the experiments when using mlos_core optimizers. now we can run, e.g., 
```bash
mlos_bench --config .\mlos_bench\mlos_bench\config\cli\azure-redis-skopt.jsonc
```
multiple times and collect the results from all runs in SQLite3 DB.

bugfix: enforce the data types for bulk_register inputs

---

.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/settings.json

stop using prettier to format json for now - it wraps two line arrays which is annoying for ranges

back out prettier config for json

---

mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_core/mlos_core/optimizers/__init__.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/emukit_optimizer.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/skopt_optimizer.py
mlos_core/mlos_core/optimizers/flaml_optimizer.py
mlos_core/mlos_core/optimizers/optimizer.py
mlos_core/mlos_core/spaces/adapters/__init__.py
mlos_core/mlos_core/spaces/adapters/adapter.py
mlos_core/mlos_core/spaces/adapters/llamatune.py
mlos_core/mlos_core/tests/optimizers/bayesian_optimizers_test.py
mlos_core/mlos_core/tests/optimizers/one_hot_test.py
mlos_core/mlos_core/tests/optimizers/optimizer_test.py
mlos_core/mlos_core/tests/spaces/adapters/identity_adapter_test.py
mlos_core/mlos_core/tests/spaces/adapters/llamatune_test.py
mlos_core/mlos_core/tests/spaces/adapters/space_adapter_factory_test.py
mlos_core/notebooks/BayesianOptimization.ipynb

As per #363 
Also fix some collateral pylint issues and remove unnecessary pylint exceptions.

Use keyword arguments in all mlos_core optimizers and space adapters

---

.github/workflows/devcontainer.yml
.github/workflows/linux.yml

Minor tweak that's helpful for CI jobs but less so for local dev loops.
See Also: https://github.com/microsoft/MLOS/blob/f7348f1c231fecd453af40f474cb9dcc5c65bda6/Makefile#L22

CI debugging tweaks: group parallel job output

---

mlos_bench/mlos_bench/config/environments/apps/redis/redis.jsonc
mlos_bench/mlos_bench/config/environments/os/linux/boot/boot-ubuntu.jsonc
mlos_bench/mlos_bench/config/environments/os/linux/runtime/setup-ubuntu.jsonc
mlos_bench/mlos_bench/config/environments/vm/azure/provision-ubuntu-vm.jsonc
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-fileshare-service-subschema.json
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-vm-service-subschema.json
mlos_bench/mlos_bench/config/services/remote/azure/service-linux-vm-ops.jsonc
mlos_bench/mlos_bench/environments/remote/os_env.py
mlos_bench/mlos_bench/environments/remote/vm_env.py
mlos_bench/mlos_bench/services/remote/azure/azure_services.py
mlos_bench/mlos_bench/services/types/vm_provisioner_type.py
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_fileshare_service-config-missing.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_vm_service-config-arm-params-bad-type-array.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_vm_service-config-arm-params-bad-type-object.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_vm_service-config-empty-arm-params.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_vm_service-config-missing.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/azure_vm_service-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/azure_fileshare_service-partial.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/azure_vm_service-partial-no-arm-params.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/azure_vm_service-partial.jsonc
mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
mlos_bench/mlos_bench/tests/services/remote/azure/conftest.py

Note that in this PR we duplicate `vmName` in all environments that use `AzureVMService`. I will move this parameter into a global config in the `CompositeEnv` in the next PR.

Migrate Azure-specific parameters from VMEnv to AzureVMService

---

mlos_bench/mlos_bench/config/schemas/environments/common-environment-subschemas.json
mlos_bench/mlos_bench/config/schemas/environments/local/local-env-subschema.json
mlos_bench/mlos_bench/config/schemas/environments/remote/remote-env-subschema.json
mlos_bench/mlos_bench/environments/local/local_env.py
mlos_bench/mlos_bench/environments/remote/remote_env.py
mlos_bench/mlos_bench/environments/script_env.py
mlos_bench/mlos_bench/services/remote/azure/azure_services.py
mlos_bench/mlos_bench/services/types/remote_exec_type.py
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_shell_params.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_shell_params_mapping.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_shell_params_mapping_type.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-non-unique-shell-params.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/remote_env-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test_environment_schemas.py
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/temp_dir_service-config-missing.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/unhandled/temp_dir_service-config-extras.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/temp_dir_service-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/temp_dir_service-partial.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test_services_schemas.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py

Presently we pass *all* Environment parameters (i.e., a combination of `const_args` and `tunable_params`) as shell env variables when we run a local or remote script. this approach has several problems:
* too many parameters leak into the shell environment;
* all names must be valid shell env variable identifiers (e.g., we crash on parameters like `ima.ahash_bufsize`)
* all values must be strings
In this PR:
* keep the old behavior by default;
* explicitly convert all values to strings and all keys to valid identifiers
* implement `ScriptEnv` base class for `RemoteEnv` and `LocalEnv` that contains `setup/run/teardown` script properties and the renaming logic for the shell script parameters
* add `shell_params` parameter so that the user can specify which parameters to pass to shell …

Explicitly specify which parameters to pass as shell env variables to the remote script

---

mlos_bench/mlos_bench/config/schemas/cli/globals-schema.json
mlos_bench/mlos_bench/config/schemas/environments/common-environment-subschemas.json
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-vm-service-subschema.json
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/mock_env-const-args-list-obj.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/mock_env-const-args-nested-list.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/partial/mock_env-const-args.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/bad/invalid/globals-with-array-with-list.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/bad/invalid/globals-with-array-with-obj.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/good/full/globals-with-schema.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_vm_service-config-arm-params-bad-type-array-object.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/azure_vm_service-full.jsonc

This allows supporting arrays in const_args, armDeploymentTemplateParams, and globals.
One use case for this are vmPort listings in ARM templates, for instance.

Support arrays for ARM templates

---

mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py

We need to define `self._temp_output_directory` at the top of the constructor because it is used later in `__del__()`/`cleanup()`

small fix to make SMAC __del__/cleanup work

---

mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py

This is the first step towards mergeable experiments. Replace missing values with the defaults when restoring trail data from storage.

Impute missing values when restoring configs from earlier experiments/trials

---

mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/tests/conftest.py
mlos_bench/mlos_bench/tests/environments/composite_env_test.py

(Old default was to use ALL tunables). @bpkroth you were right about this one

Do not inherit any tunables if `tunable_params` not specified.

---

mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/experiment.py
mlos_bench/mlos_bench/tests/storage/exp_load_test.py

Before that, we loaded only the data from successful runs.
We probably need to merge #412 and #407 before this one

Bulk load the data of failed and timed out trials into the optimizer

---

mlos_bench/mlos_bench/tunables/tunable.py

We'll need it for many things, but right now the plan is to store the units and scalers for some tunable values and use it for MySQL, e.g., to produce config values like `innodb_buffer_pool_size = 128M`

introduce the "meta" field in Tunable class

---

.github/workflows/devcontainer.yml

Closes #396
Whatever was going on previously seems to be fixed now and the rebuilds I've looked at all finished in tens of seconds like they're supposed to.  This fixup isn't strictly required, but is a good test on our internal scripts.

Lower the devcontainer rebuild timeout again

---

mlos_core/mlos_core/__init__.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
mlos_core/mlos_core/optimizers/optimizer.py
mlos_core/mlos_core/spaces/adapters/llamatune.py
mlos_core/mlos_core/tests/spaces/adapters/llamatune_test.py
setup.cfg

Some improvements for tight dev cycle and making debugging easier by cleaning up some noise:
- Fix some pytest DeprecationWarnings
- Ignore some others that aren't in our code.
- When rerunning pytest, run the last failed or new tests first.

Pytest warnings fixups

---

mlos_core/mlos_core/tests/spaces/spaces_test.py

The issue was on my side - I'd forgotten to remove a ceil patch from my local flaml install.
The int log uniform test still fails, but that's a separate issue.

Enable float uniform log test for flaml

---

mlos_bench/mlos_bench/config/schemas/config_schemas.py
mlos_bench/setup.py

Updates our json schema resolution code to use the referencing lib per upstream updates.
Closes #437 
See Also: https://python-jsonschema.readthedocs.io/en/stable/referencing/#migrating-from-refresolver

json schema resolution referencing lib updates

---

mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/environments/composite_env.py
mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/tests/environments/include_tunables_test.py
mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py

Summary of changes:
* Do not mutate the parent collection of tunables when loading them from a file.
* Fix the confusing behavior of the environment: we did not assign the new values to the environment's tunables after `.setup()`. That is ok most of the time as we never use the tunables alone when setting up the environment (we merge them into `self._params` along with `const_args` and globals), but it is still a bit confusing to not update the tunables on setup.
* Add unit tests to check the new behavior.
* Add logging statements to debug the issue

Bugfix: update the env tunable values in setup, do not mutate the parent when loading the tunables

---

.vscode/settings.json
mlos_bench/mlos_bench/config/schemas/environments/local/local-env-subschema.json
mlos_bench/mlos_bench/environments/local/local_env.py
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_fileshare_env-full.jsonc

In the subsequent PRs, we will port the tunables' metadata and Linux kernel configuration scripts that use it from our private repo.
A PR with unit tests will also follow (turns out, we don't have *any* tests for `LocalEnv` atm).

Dump the tunables' metdata to JSON file so that the `LocalEnv` scripts can use it

---

mlos_bench/mlos_bench/optimizers/base_optimizer.py
mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/experiment.py

Introduce `--configId` command line option, e.g., 
`mlos_bench --config config/cli/cli-azure-mysql-bench.jsonc --globals experiment_mysql-kernel-hp.jsonc --configId 377`
Also, do not preload the existing results or resume pending trials if we just want to run a single benchmark.

Add the ability to re-run the benchmark for configurations already in DB

---

scripts/generate-azure-credentials-config.ps1
scripts/generate-azure-credentials-config.sh

This allows one to use something like 
```sh
az config set defaults.group=myRG --local
```
To configure the RG and storage account to use for `az` commands executed in the local directory, reducing some environment setup between shell invocations (e.g. needing to source an `env.sh` file for instance).

Support pulling Azure configs from local dir

---

mlos_bench/mlos_bench/environments/composite_env.py

There is a bug in `CompositeEnv` constructor that prevents the parent's tunables to be pushed down into the child environments. In particular, the tunables from `"include_tunables"` in the composite environments are not available to all children without mixing them into the `CompositeEnv._tunable_params`. 
That issue makes impossible some perfectly legitimate configs, e.g.,
```jsonc
{
"name": "Setup Ubuntu VM",
"class": "mlos_bench.environments.composite_env.CompositeEnv",
"include_tunables": ["environments/os/linux/runtime/linux-runtime-tunables.jsonc"],
"config": {
"children": [
{
"name": "Generate Linux kernel parameters for Ubuntu",
"class": "mlos_bench.environments.LocalFileShareEnv",
"config": {
"tunable_params": ["$linux-runtime"],
// ... etc.
```
Note that `"include_tunables"` is …

Make "include_tunables" work for composite environments

---

mlos_bench/mlos_bench/services/local/local_exec.py

Checking for an actual executable is a bit tricky on Windows, so we'll do it properly later; (also, it is ok to have X bits not set for Python scripts). For now, add some minimal checks to prevent `.` (as in `. script.sh`) from expanding into a current directory path instead of being treated as `source script.sh` in bash.
Also, remove extra newlines when logging the script's stdout/stderr.

bugfix: do not expand the script path in run/setup/teardown if it is not executable

---

mlos_bench/mlos_bench/environments/local/local_env.py

The LocalEnv.run() function processed any results DataFrame containing a single record as a scalar record. This change ensures that even if the result file contains a single line of the form `(metric, value)`, it is processed as a dictionary.

bugfix: Process result files of the form (metric, value) as dictionaries or scalar with the column name score

---

.vscode/settings.json
mlos_bench/mlos_bench/config/environments/apps/redis/redis.jsonc
mlos_bench/mlos_bench/config/environments/os/linux/boot/boot-ubuntu.jsonc
mlos_bench/mlos_bench/config/environments/os/linux/runtime/setup-ubuntu.jsonc
mlos_bench/mlos_bench/config/experiments/README.md
mlos_bench/mlos_bench/config/experiments/experiment_RedisBench.jsonc
mlos_bench/mlos_bench/config/schemas/cli/cli-schema.json
mlos_bench/mlos_bench/config/schemas/cli/common-defs-subschemas.json
mlos_bench/mlos_bench/config/schemas/cli/globals-schema.json
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-vm-service-subschema.json
mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/tests/config/cli/mock-bench.jsonc
mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
mlos_bench/mlos_bench/tests/config/environments/test_load_environment_config_examples.py
mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/invalid-experiment-id.jsonc
mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/wrong-schema-path.jsonc
mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/unhandled/cli-with-extras.jsonc
mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/good/full/full-cli.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/bad/invalid/globals-tunable-values-disallowed.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/bad/invalid/globals-with-bad-experiment-id.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/bad/invalid/globals-with-bad-trial-id.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/good/full/globals-with-schema.jsonc
mlos_bench/mlos_bench/tests/config/schemas/globals/test-cases/good/partial/globals-with-null.jsonc
mlos_bench/mlos_bench/tests/storage/trial_config_test.py

Adds schema restrictions on experiment_id since we use (or plan to use) it in path names.
Per #357, also renames for snake case consistency.

experiment_id fixups and restrictions

---

.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/settings.json
conda-envs/mlos-3.10.yml
conda-envs/mlos-3.11.yml
conda-envs/mlos-3.8.yml
conda-envs/mlos-3.9.yml
conda-envs/mlos-windows.yml
conda-envs/mlos.yml

The recommended autopep8 extension doesn't seem to be working for us:
https://github.com/microsoft/vscode-autopep8/issues/16
So, for now I'm reverting to the old way of doing things.
Also, the previous extension relied on a newer version of autopep8 than conda was installing anyways, so I switched to installing it from pip.

Autopep8 devcontainer fixups

---

mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/optimizers/base_optimizer.py
mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/optimizers/mock_optimizer.py
mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
mlos_bench/mlos_bench/services/base_service.py
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/storage.py

For supporting `experiment_id` as `run_name` in #470.
Future work:
- Consolidate global_config variable expansion recursively and in other configs.

mlos_bench: pass global_config to remaining base classes

---

mlos_bench/mlos_bench/tests/config/cli/mock-opt.jsonc
mlos_bench/mlos_bench/tests/launcher_test.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py

By default, SMAC overrides the logging configuration and that prevents mlos_bench from writhing to a log file in proper format. This PR fixes the issue and also adds a test configuration file to run the optimizer.
Closes #475

Fix SMAC optimizer logging issue

---

mlos_bench/mlos_bench/config/schemas/environments/local/local-env-subschema.json
mlos_bench/mlos_bench/environments/README.md
mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/environments/composite_env.py
mlos_bench/mlos_bench/environments/local/local_env.py
mlos_bench/mlos_bench/environments/local/local_fileshare_env.py
mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/services/remote/azure/azure_fileshare.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_fileshare_env-full.jsonc

Summary of changes:
* Add `"read_telemetry_file"` parameter to `LocalEnv` implement the telemetry reading functionality
* Allow failures when downloading (intermediate) files in `LocalFileShareEnv`
* Translate Azure-specific exceptions in `AzureFileShareService` to the generic ones to keep Environment classes cloud-agnostic
* Bugfix: implement `CompositeEnv.status()` properly
**TODO:**

Implement "read_telemetry_file" feature

---

mlos_core/mlos_core/optimizers/__init__.py

We've found that SMAC has some non-determinism and incomplete integration, which causes some issues with our pipelines and experiment results, so for now we switch back to FLAML as the default.

Switch back to FLAML as the default optimizer

---

mlos_bench/mlos_bench/config/experiments/experiment_RedisBench.jsonc
mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/tests/config/cli/mock-bench.jsonc
mlos_bench/mlos_bench/tests/config/cli/mock-opt.jsonc
mlos_bench/mlos_bench/tests/config/globals/global_test_config.jsonc

This feature greatly simplifies our configs for complex multi-VM setups.
P.S. I cannot come up with any simple and elegant unit tests for this feature. Technically, we can define some dollar variables in `global_test_config.jsonc` and check their values in the log in `launcher_test.py`, but we don't have that many parameters in `MockEnv` and `MockOptimizer` that we can expand. I'll think about it and do it in the next PR.

Expand dollar variables in the globals

---

.vscode/launch.json
mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/tests/optimizers/conftest.py
mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
mlos_core/mlos_core/optimizers/optimizer.py
mlos_core/mlos_core/tests/optimizers/optimizer_test.py
setup.cfg

- Workaround a bug in SMAC that builds additional_configs across instantiations.
- Adds more assertions to help check for related issues
- Addresses a TODO sanity check
- Adds some test code for FLAML's surrogate model by increasing iterations
- Updates tests for easier tracing
Note: This still doesn't address all of the non-determinism across platforms/python versions we've noticed recently (#482), and there's some question yet about how much runhistory and some other features are being handled correctly, but this still handles a few small improvements of other issues I've noticed.
For the rest I've filed issues: 
- #487  
- #488

Smac optimizer bugfixes

---

.devcontainer/build/Dockerfile
.github/workflows/devcontainer.yml

Something changed in the baseimage and now the uid/gid that the github runners use already exists in the base image of the devcontainer-cli.
To workaround that we just allow for `--non-unique`ness

Workaround a devcontainer uid/gid conflict in the Github CI pipelines

---

mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-vm-service-subschema.json
mlos_bench/mlos_bench/config/services/remote/azure/arm-templates/azuredeploy-ubuntu-vm.jsonc
mlos_bench/mlos_bench/config/services/remote/azure/cloud-init/alt-ssh.yml
mlos_bench/mlos_bench/services/remote/azure/azure_services.py
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/azure_vm_service-full.jsonc
mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py

Adds support to allow reading `customData` out of a file to pass to the ARM templates.
This way we can code `cloud-init` files (for example) separately with all the usual syntax help, rather than embed them in JSON configs.

Support customData file to pass to ARM templates

---

.devcontainer/Dockerfile

Also brings devcontainer inline with rules for Linux Github Actions and adds some debugging output for future.
Addresses NO_CACHE build issues that were failing in local rebuilds and nightly scheduled actions.

Workaround an upstream conda vs. base devcontainer image dependency mismatches

---

mlos_bench/mlos_bench/services/remote/azure/azure_fileshare.py

Fix for #505 when parent folders do not exist in the remote file share yet during an upload.

Fix azure fileshare uploading of directories

---

.github/workflows/devcontainer.yml

Handles bugs from #508.
Also try and fix a quoting issues.

Fixups to commit message checks to only happen during PR pushes

---

.github/workflows/devcontainer.yml

One more minor tweak on #509 and #508.  This allows us to force a rebuild of the devcontainer with NO_CACHE=true manually without needing to push an empty commit.

No cache support for manual devcontainer build triggers

---

.github/workflows/devcontainer.yml
mlos_bench/mlos_bench/tests/environments/local/__init__.py
mlos_bench/mlos_bench/tests/environments/local/composite_local_env_test.py
mlos_bench/mlos_bench/tests/environments/local/local_env_stdout_test.py
mlos_bench/mlos_bench/tests/environments/local/local_env_telemetry_test.py
mlos_bench/mlos_bench/tests/environments/local/local_env_test.py
mlos_bench/mlos_bench/tests/environments/local/local_env_vars_test.py

Also, rename some local functions to reflect the fact that the environment may not necessarily be an instance of `LocalEnv` and change the docstrings and annotations accordingly.
Closes #501

Unit tests for combining the results of several `LocalEnv`s in one `CompositeEnv`

---

conftest.py
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-auth-service-subschema.json
mlos_bench/mlos_bench/config/schemas/services/remote/mock/mock-auth-service-subschema.json
mlos_bench/mlos_bench/config/schemas/services/service-schema.json
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_auth_service-config-missing.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/azure_auth_service-partial.jsonc
mlos_bench/mlos_bench/tests/config/services/remote/mock/mock_auth_service.jsonc

Adjusts service schema's to not require an empty `"config": {}` element, and instead only include it if there's some other property in it.
Split out from #510

Don't require empty config element in service json schemas

---

mlos_bench/mlos_bench/environments/local/local_fileshare_env.py
mlos_bench/mlos_bench/services/base_fileshare.py
mlos_bench/mlos_bench/services/remote/azure/azure_fileshare.py
mlos_bench/mlos_bench/services/types/fileshare_type.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_fileshare_test.py
mlos_bench/mlos_bench/tests/services/remote/mock/mock_fileshare_service.py

Required for SshFileShareService to know which host to connect to.
See Also: #510

Add params support to upload/download ops for fileshare service types

---

mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
mlos_bench/mlos_bench/tests/services/local/local_exec_test.py

Fixup to Windows test for bug introduced by #529
Need to canonicalize paths to use `/` instead of `\\` when doing comparisons.

Canonicalize the path for test comparison purposes

---

mlos_bench/mlos_bench/launcher.py
mlos_core/mlos_core/optimizers/__init__.py
mlos_core/mlos_core/spaces/adapters/__init__.py

Follow on to #529 
Allows for environment variables to be used in the globals config file like so:
```json
"CONTAINER_WORKSPACE_FOLDER": "$CONTAINER_WORKSPACE_FOLDER",
"LOCAL_WORKSPACE_FOLDER": "$LOCAL_WORKSPACE_FOLDER",
```
So that the value can be pulled directly from the shell environment without having to invoke `mlos_bench` with those values explicitly like this:
~`mlos_bench --config ... --globals ... --CONTAINER_WORKSPACE_FOLDER=$CONTAINER_WORKSPACE_FOLDER --LOCAL_WORKSPACE_FOLDER=$LOCAL_WORKSPACE_FOLDER`~

Reverse order of preference for environment variable expansion.

---

mlos_bench/mlos_bench/storage/sql/experiment_data.py

without this fix, our Jupyter notebook for ADU SQLite optimization demo would fail

bugfix: allow non-numeric values in trial results data

---

.github/workflows/devcontainer.yml
.vscode/settings.json
Makefile
mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
setup.cfg

Fixes a bug with mock responses not providing a `json()` method which is only called during debug logging.
This was somewhat randomly showing up based I think upon the order of the tests running.
One of them, seemed to be enabling `_LOG.setLevel(logging.DEBUG)` so that future tests (for that worker) would also have the level set.
Once done, additional paths would be followed inside the `AzureServices` code that caused it to try and do something like the following `_LOG.debug(response.json())` which would fail because the mocked response object didn't provide a `json()` method response.
This fixes that error, but doesn't address the `debug` log ordering.
I'm not certain we should switch all of our unit tests over to running in DEBUG mode by default since it might cause us to depend on that …

Fix intermittent MagickMock response unit test error

---

mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/trial.py
mlos_bench/mlos_bench/tests/storage/exp_load_test.py

This is for basic functionality only. We'll have more tests in the next PR where we test the the new `storage.experiments[]` API
Closes #539

Add unit tests for multi-score updates. Allow non-numeric metrics in storage type annotations.

---

mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/services/base_fileshare.py
mlos_bench/mlos_bench/services/base_service.py
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/services/local/local_exec.py
mlos_bench/mlos_bench/services/local/temp_dir_context.py
mlos_bench/mlos_bench/services/remote/azure/azure_auth.py
mlos_bench/mlos_bench/services/remote/azure/azure_fileshare.py
mlos_bench/mlos_bench/services/remote/azure/azure_services.py
mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_2.jsonc
mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_3.jsonc
mlos_bench/mlos_bench/tests/environments/composite_env_service_test.py
mlos_bench/mlos_bench/tests/services/local/mock/mock_local_exec_service.py
mlos_bench/mlos_bench/tests/services/remote/mock/mock_auth_service.py
mlos_bench/mlos_bench/tests/services/remote/mock/mock_fileshare_service.py
mlos_bench/mlos_bench/tests/services/remote/mock/mock_remote_exec_service.py
mlos_bench/mlos_bench/tests/services/remote/mock/mock_vm_service.py

**UPDATE:** Fixed! The problem was with the `.register()` method invocation in the base class constructor, so the service can inherit methods from the parent service. That call overrode methods of the service object being created with references to the parent's methods. As a result, we were losing references to the local methods before we could register them. This PR is a workaround for the issue. We will think of a more elegant way of doing it later.
-------------------
Debugging and fixing the issue described in #530
**TODO:**

Fix the nested service inclusion issue + add unit tests

---

.vscode/launch.json
.vscode/settings.json

This change makes it so that running tests via VSCode's pytest plugin by default runs them in parallel (respecting the setup.cfg args for pytest), but when using the "Debug Test" option, parallel workers are disabled so we can more quickly trace through code in debug mode without additional processes to attach to.
Unfortunately, there is a [bug with the pytest-xdist loadgroup output processing in the vscode](https://github.com/microsoft/vscode-python/issues/19374) that prevents a few tests that use that (namely the recently added ssh test) from displaying as "completed successfully", even though they did.

Tweaks to debug vs. batch run testing in VSCode

---

.devcontainer/docker-compose.yml

Addresses an error introduced by #552 
```
The Compose file '/var/lib/docker/codespacemount/workspace/MLOS/.devcontainer/docker-compose.yml' is invalid because:
services.app.build contains unsupported option: 'tags'
```

codespaces's docker-compose version doesn't support tags for build args

---

mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_2.jsonc
mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_3.jsonc
mlos_bench/mlos_bench/tests/environments/composite_env_service_test.py

also, make the temp directory names a bit more unique to avoid clashes. P.S. we cannot use paths like `/tmp/...` because it won't work on Windows

Clean-up temp directories created in unit tests

---

mlos_bench/mlos_bench/config/schemas/environments/common-environment-subschemas.json
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_script_params_mapping.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_script_params_mapping_type.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/remote_env-full.jsonc

Remove unused parameters like `shell_env_params_match` and `shell_env_params_mapping`; add `shell_env_params_rename`

Update json schema to the actual parameters of script_env

---

mlos_bench/mlos_bench/tests/config/globals/global_test_config.jsonc
mlos_bench/mlos_bench/tests/launcher_parse_args_test.py

Previously #553 solved this for pytest inside VSCode for WSL, devcontainer within WSL, and Windows directly dev environments by looking at the `$VSCODE_CWD` environment variable that the Pytest VSCode extension sets to note the difference between the expected environment variable `$PWD` and the result of `os.getcwd()`.
However, when the devcontainer is launched from Windows, the VSCode pytest plugin takes a different approach and launches a proxy server in WSL to run the tests. In that mode, `$VSCODE_CWD` is still set but is no longer the path used.
To avoid fighting with all these different scenarios, we change the test to set `$CUSTOM_PATH_FROM_ENV` via `os.environ` prior to the start of the test, and then make sure that it's expanded when we use it inside `global_test_config.jsonc` …

Fixup issues with VSCode and pytest working directory paths in different environments

---

mlos_bench/mlos_bench/event_loop_context.py
mlos_bench/mlos_bench/services/remote/ssh/ssh_service.py
mlos_bench/mlos_bench/tests/event_loop_context_test.py

Tries to handle a few issues we've seen with the event loop code.
In particular, Windows sometimes hangs and seems to have lingering coroutines (sometimes added by it's default ProactorEventLoopPolicy).
This change adds some additional tests and debug code and switches to the SelectorEventLoopPolicy for Windows.
Note: this comes with some drawbacks like not being able to handle subprocesses in async code, which could prove to be a problem for us with parallel executors in the future:
https://docs.python.org/3/library/asyncio-platforms.html#windows

Fix asyncio issues

---

scripts/generate-azure-credentials-config.sh

Allow overriding which RG to look for the storage account in when separating experiment RG from control plane RG

Allow storage RG override for separate control plane RG vs experiment RG

---

.vscode/settings.json

My VSCode adds `"."` to pytest arguments in config every time I rebuild the container - and deletes the `--log-level=DEBUG` argument at teh same time. With this small fix, vscode can accept the project config as we have it in git without modifying it

Explicitly add the project root to pytest arguments

---

mlos_bench/mlos_bench/services/remote/azure/azure_services.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
scripts/generate-azure-credentials-config.sh

This PR enables automatic retry and backoffs for HTTP requests made using requests, mainly targeting GETs.
This is to address intermittent connection issues observed during long-running operations such as polling, which would have resulted in OSErrors crashing MLOS and ending experiments prematurely.
The main patterns used are:
- https://docs.python-requests.org/en/latest/user/advanced/#example-automatic-retries
- https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.retry

Retries for HTTP requests

---

Makefile

Corrects this error:
```
---------- coverage: platform linux, python 3.11.5-final-0 -----------
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
Required test coverage of 0.92% reached. Total coverage: 93.12%
=========================== short test summary info ============================
```

Enforce correct code coverage threshold

---

.cspell.json
mlos_bench/mlos_bench/dict_templater.py
mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/services/remote/azure/azure_vm_services.py
mlos_bench/mlos_bench/tests/dict_templater_test.py
mlos_bench/mlos_bench/tests/environments/base_env_test.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py

Fixes extracted from #606 
This expands support for doing secondary `$var` string template expansion to two additional places beyond `global_config`:
- `const_args`
- `deploymentTemplateParameters` in `AzureVmService` (and soon `AzureNetworkService`)
Expands a few test cases to check for this and relies on one prior existing one to still pass (the `launch_parse_args` tests which already checked for this behavior in `global_config` expansion).

Add support for recursive dictionary templating to more places

---

mlos_bench/mlos_bench/dict_templater.py
mlos_bench/mlos_bench/os_env.py
mlos_bench/mlos_bench/os_environ.py
mlos_bench/mlos_bench/services/local/local_exec.py
mlos_bench/mlos_bench/tests/dict_templater_test.py
mlos_bench/mlos_bench/tests/launcher_parse_args_test.py

Fixes a bug introduced in #614 for Windows tests.
On Windows, 
```python
os.environ["string"] = "str"
```
internally gets replaced as
```python
os.environ["STRING"]
```
The workaround is to use `nt.environ` on Windows instead.
This change introduces an abstraction to use a new simple drop in replacement library everywhere we need to handle environment variables.

Abstract OS environment variable case sensitivity name handling across platforms

---

mlos_bench/mlos_bench/tests/tunables/test_tunable_categoricals.py
mlos_bench/mlos_bench/tunables/tunable.py

Improvements on #549 
- Handles the case where the default for a tunable is `False` (else it wouldn't be converted to a `str`).
- Adds more details during debug and error output to make troubleshooting easier

Tunable fixups

---

mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/storage/base_experiment_data.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/base_trial_data.py
mlos_bench/mlos_bench/storage/sql/experiment.py
mlos_bench/mlos_bench/storage/sql/trial_data.py

Minor tweaks to make it easier to understand the difference between a (tunable) config (for an Environment) and a config (part of the framework) when interacting with the storage layer (who's schema switches terminology slightly than the code).

Rename and improve tunable vs config API and documentation

---

.bumpversion.cfg
.github/workflows/devcontainer.yml
doc/source/conf.py
mlos_bench/_version.py
mlos_core/_version.py

Minor tweak on #626: instead of acting on tag push events, we only act on "release" events.  This gives us a chance to fix bad tag pushes (which otherwise don't have much gated checking on them) prior to attempting to publish a version on pypi, which cannot be overwritten (only superseded).

CI tweak: use "release" event instead of "tag push" for pypi publishing

---

.pylintrc

Tell pylint to ignore FIXME comments in our code.

---

mlos_bench/mlos_bench/optimizers/convert_configspace.py
mlos_bench/mlos_bench/tests/optimizers/conftest.py
mlos_bench/mlos_bench/tests/optimizers/mlos_core_opt_df_test.py
mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py

Add unit tests for `MlosCoreoptimizer._to_df()` functionality; use special values in tunables

---

mlos_bench/mlos_bench/config/schemas/tunables/tunable-params-schema.json
mlos_bench/mlos_bench/tests/config/schemas/tunable-params/test-cases/bad/invalid/tunable-params-bad-name.jsonc

Disallow `!` characters in tunable parameter names.

---

mlos_bench/mlos_bench/config/schemas/cli/cli-schema.json
mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/good/full/full-cli.jsonc
mlos_bench/mlos_bench/tests/launcher_run_test.py

Adds very rudimentary support for repeating configs across multiple trials.  We fully expect to expand on more advanced support for this once we add a proper scheduler (#463).
Additional tests forth coming with #633 and related PRs.

Add basic support for repeating a trial config.

---

.bumpversion.cfg
Makefile
doc/source/conf.py
mlos_bench/_version.py
mlos_core/_version.py

Prior Makefile rule consolidation tried to group dependencies for the pattern rule into separate lines for readability, but apparently this isn't allowed.
This minor changes separates those out into a variable we can reference instead.  Tested on a clean build tree locally.

PyPi publish makefile rules fixup

---

mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/storage/base_experiment_data.py
mlos_bench/mlos_bench/storage/sql/experiment_data.py
mlos_bench/mlos_bench/tests/storage/exp_data_test.py

Splitting work out from #633.
Having an easy way to identify what is the "default" config group for an Experiment makes analysis of improvements easier.
One challenge with this is that we don't currently strictly enforce non-changes between resumptions of an Experiment, so it's currently possible for the user to change the tunables config and adjust what the "default".
Moreover, in the past we didn't store what the default config was in the DB.
By convention we take the first one for now as a fallback.

Add `default_tunable_config_id` property to `ExperimentData`

---

mlos_bench/mlos_bench/storage/sql/schema.py

#628 mistakenly included an early attempt at adding `optimization_target` and `optimization_direction` to the `experiment` table in the `mlos_bench.storage.sql` backend.
In that PR we later moved it to its own `objectives` table to eventually support multi-objectives.
Nothing accesses those columns now, however including them in the metadata makes it impossible to load storage backends previously created with the old schema since adjusting columns with sqlalchemy's `create_all()` API only considers table existence.
On the contrary, the latter means that we will automatically support old storage backends with the new code for the `objectives` table.
Removing these two columns in the `metadata` schema description simply allows that to proceed without error.
See Also: #649

Remove mistakenly added columns

---

mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/optimizers/base_optimizer.py
mlos_bench/mlos_bench/tests/config/cli/test-cli-config.jsonc
mlos_bench/mlos_bench/tests/launcher_parse_args_test.py

Splitting work out from #633.
Bug fix for #642.

Fixes to `max_iterations` calculation when `trial_config_repeat_count` is given.

---

mlos_bench/mlos_bench/environments/local/local_env.py
mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/storage/sql/common.py

Polish for a demo.
See Also: https://stackoverflow.com/a/61185987

Address some pandas FuturesWarnings

---

mlos_bench/setup.py

See Also:
- https://github.com/TvoroG/pytest-lazy-fixture/issues/65
- https://github.com/pytest-dev/pytest/issues/11890

Workaround pytest version bump incompatibility with pytest-lazy-fixtures plugin

---

.github/workflows/devcontainer.yml

Fixes our documentation deploy step in the CI pipeline, which is currently failing due to a change to the default permissions of the `GITHUB_TOKEN` which is now read-only unless otherwise specified.

Reorg doc deploy step for new GITHUB_TOKEN permissions requirements

---

Makefile

Omit tests from docs

---

mlos_bench/mlos_bench/storage/util.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
mlos_core/mlos_core/optimizers/flaml_optimizer.py
mlos_core/mlos_core/spaces/adapters/llamatune.py
mlos_core/mlos_core/tests/__init__.py
mlos_core/mlos_core/tests/optimizers/optimizer_test.py

Addressing issue discussed in #666

Fix mixed numeric datatypes for optimizers

---

.bumpversion.cfg
doc/source/conf.py
mlos_bench/_version.py
mlos_core/_version.py

Let's cut a new minor release with the new functionality we've merged in this week.

Bump version: 0.4.2 → 0.5.0

---

mlos_core/mlos_core/optimizers/optimizer.py
mlos_core/mlos_core/tests/optimizers/one_hot_test.py

Our one hot encoding previously had some conditional handling of 1 dimensional DataFrames.
That doesn't exist - those are Series.  As such, the typing returns recently started alerting (due to an upstream dependency bump).
Moreover, we lacked test coverage for that path.
This change makes it more clear what those type expectations are and adds tests.

Handle some mypy errors and increase test coverage

---

mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-deployment-service-subschema.json
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-network-service-subschema.json
mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-vm-service-subschema.json
mlos_bench/mlos_bench/services/remote/azure/azure_deployment_services.py
mlos_bench/mlos_bench/services/remote/azure/azure_network_services.py
mlos_bench/mlos_bench/services/remote/azure/azure_vm_services.py
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_vm_service-config-missing.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/azure_vm_service-partial-no-deployment.jsonc
mlos_bench/mlos_bench/tests/config/schemas/services/test_services_schemas.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_network_services_test.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_vm_services_test.py
mlos_bench/mlos_bench/tests/services/remote/azure/conftest.py

i.e., don't require `deploymentTemplatePath`
Additionally, rename some things to make it more clear that the base class is just for deployment services.
Note, an alternative approach discussed was to separate the AzureVmServices class into a "provisioning" and "ops" set of services, but that likely would have broken some existing configs, so we took this smaller approach.

Allow use of Azure VM Service for only remote exec.

---

mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/optimizers/base_optimizer.py
mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/optimizers/mock_optimizer.py
mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/experiment.py
mlos_bench/mlos_bench/tests/launcher_in_process_test.py
mlos_bench/mlos_bench/tests/launcher_run_test.py
mlos_bench/mlos_bench/tests/storage/exp_load_test.py
mlos_bench/mlos_bench/tests/storage/trial_schedule_test.py

Initial work to support pluggable Schedulers (#679).
This starts by adding the necessary support to auxiliary classes and splits the current simple run/optimize loop into two stages.
Future PRs will expand on this to separate abstract and configurable classes for more flexible scheduling policies.

Initial work to separate the scheduler and the optimizer (no async yet)

---

.devcontainer/Dockerfile

A new base devcontainer image was [released](https://github.com/devcontainers/images/blob/main/src/miniconda/history/0.203.7.md) recently that introduces the following error in our environment when running `make test`:
```
import pandas._libs.window.aggregations as window_aggregations\n'
'ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version '
"`GLIBCXX_3.4.29' not found (required by "
'/opt/conda/envs/mlos/lib/python3.11/site-packages/pandas/_libs/window/aggregations.cpython-311-x86_64-linux-gnu.so)\n')
```
A simplified reproduction involves running `conda run -n mlos pytest mlos_bench/mlos_bench/launcher_run_test.ph`.
Unfortunately, it appears that under the latest version somewhere between `conda` and `pytest` the `libc.so.6` library found is the one under `/usr/lib` instead …

Pin a devcontainer version to workaround library search path issue

---

mlos_bench/mlos_bench/optimizers/base_optimizer.py
mlos_bench/mlos_bench/storage/util.py
mlos_bench/mlos_bench/tests/tunables/tunable_definition_test.py
mlos_bench/mlos_bench/tests/tunables/tunable_distributions_test.py
mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
mlos_bench/mlos_bench/tunables/tunable.py

Some type hint and alias tweaks for Tunables and a few others.
Split off from #690.

Typing tweaks

---

mlos_bench/mlos_bench/tests/tunables/test_tunables_size_props.py
mlos_bench/mlos_bench/tunables/tunable.py

Adds support for introspecting the values from a quantized or otherwise discrete Tunable.
Split out from #690.

Add cardinality and size related properties to Tunables

---

.github/workflows/devcontainer.yml

Fixup following the commit message from #699 which includes a backtick command.

Don't shell interpret commit messages

---

mlos_bench/mlos_bench/services/local/local_exec.py

Roll back one of the updates from #705 
It breaks tests on both Windows and WSL DevContainer on my PC.
* On Windows, `environ` may not have `PATH` at all
* On my WSL DevContainer, passing non-null `env` to `subprocess.run` prevents it from finding the right python interpreter

Roll back forceful assignment of PATH when invoking a local process

---

mlos_core/mlos_core/tests/optimizers/one_hot_test.py

another PR to reduce the size of #730

make optimizer a fixture for 1-hot encoding/decoding tests

---

.devcontainer/Dockerfile
conda-envs/mlos-3.10.yml
conda-envs/mlos-3.11.yml
conda-envs/mlos-3.8.yml
conda-envs/mlos-3.9.yml
conda-envs/mlos-windows.yml
conda-envs/mlos.yml
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
mlos_core/mlos_core/optimizers/flaml_optimizer.py
mlos_core/mlos_core/spaces/adapters/llamatune.py
mlos_core/mlos_core/spaces/converters/flaml.py
mlos_core/mlos_core/tests/spaces/spaces_test.py
mlos_viz/mlos_viz/base.py

A new git version outputs a different date format that older versions of python's datetime module don't recognize.
https://github.com/pypa/setuptools_scm/issues/1038
setuptools-scm cut a new version to address that, but it's not available in conda main channel yet, which is required, since without that the conda pip phase can't execute in a single transaction
For now, we install things via conda-forge and adjust the channel priority order so that the full set of dependencies could be resolved.
That of course brought in additional changes (e.g., `python=3.12` by default, new `pylint`, `pycodestyle`, etc.), so this now also includes some additional linting changes.
However, longer term, we need to switch to a pyproject.toml file to fix this properly. 
There we can specify prereqs for even …

Cascading series of CI dependency problems

---

.github/workflows/codeql.yml
.github/workflows/devcontainer.yml
.github/workflows/linux.yml
.github/workflows/markdown-link-check.yml
.github/workflows/windows.yml

Saves some resources and should speed up PRs that push frequently.
https://docs.github.com/en/actions/using-jobs/using-concurrency

Limit CI concurrency

---

mlos_bench/mlos_bench/config/environments/apps/redis/redis.jsonc

These missing environment variables were causing the Redis benchmark to fail.

Added missing 'shell_env_params' in redis.jsonc

---

.vscode/settings.json
mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/bayesian_optimizer.py
mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
mlos_core/mlos_core/optimizers/flaml_optimizer.py
mlos_core/mlos_core/optimizers/optimizer.py
mlos_core/mlos_core/optimizers/random_optimizer.py
mlos_core/mlos_core/tests/optimizers/bayesian_optimizers_test.py
mlos_core/mlos_core/tests/optimizers/one_hot_test.py
mlos_core/mlos_core/tests/optimizers/optimizer_multiobj_test.py
mlos_core/mlos_core/tests/optimizers/optimizer_test.py

This is a simple PR that makes all arguments explicit for optimizer-related function calls in preparation to add additional arguments in #751 and make it easier to review.

Require explicit arguments for mlos_core optimizers

---

mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py

Minor tweak to address this warning in pytest output:
```
mlos_core/mlos_core/tests/optimizers/optimizer_multiobj_test.py::test_multi_target_opt_wrong_weights[SmacOptimizer-kwargs2]
C:\Users\bpkroth\.conda\envs\mlos\Lib\site-packages\_pytest\unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <function SmacOptimizer.__del__ at 0x0000021F5FDC42C0>
Traceback (most recent call last):
File "C:\Users\bpkroth\src\MLOS\mlos_core\mlos_core\optimizers\bayesian_optimizers\smac_optimizer.py", line 208, in __del__
self.cleanup()
File "C:\Users\bpkroth\src\MLOS\mlos_core\mlos_core\optimizers\bayesian_optimizers\smac_optimizer.py", line 339, in cleanup
if self._temp_output_directory is not None:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SmacOptimizer' object has no …
```

Cleanup a warning issued by the SmacOptimizer cleanup code

---

Makefile

- Introduce a new `make format` target that currently only calls `licenseheaders` but will call `isort` and `black` in the future
- Introduce new variables to help make dependency tracking easier
- Simplify `pytest` rules and allow running only a single module at a time.
This PR is a precursor to pyproject.toml related build changes as well.

Staged Makefile Improvements

---

mlos_bench/mlos_bench/schedulers/base_scheduler.py

bugfix: is_defaults() is a method, not property

---

mlos_bench/mlos_bench/os_environ.py
mlos_bench/mlos_bench/storage/sql/experiment.py

Solution: truncate microseconds of the current timestamp when scheduling new trials to be executed ASAP
Closes #756

bugfix: MySQL can round microseconds into the future causing scheduler to skip trials

---

mlos_bench/mlos_bench/config/schemas/tunables/tunable-params-schema.json
mlos_bench/mlos_bench/tunables/README.md
mlos_core/setup.py

ConfigSpace 1.0.0 was just released and includes some important changes that we'll eventually want to support, but in the interest of making progress on other things for the time being, this PR pins us at the previous stable version we were using.
https://github.com/automl/ConfigSpace/compare/v0.7.2...v1.0.0

Temporarily restrict ConfigSpace version

---

.git-blame-ignore-revs

Follow-on work to #774, this PR uses a [`.git-blame-ignore-revs` file](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) to ignore revs that cause major reformatting changes in git blame view.

Ignore reformatting revision

---

mlos_core/mlos_core/tests/optimizers/optimizer_test.py
mlos_core/mlos_core/tests/spaces/adapters/space_adapter_factory_test.py

Mypy got updated to v 1.11 recently
We need these mypy fixes to make other PRs pass the CI tests

Fix mypy 1.11 warnings

---

mlos_core/setup.py
mlos_viz/setup.py

- Upgrade to a newer version of dabl with better sklearn support and explicit dependencies for some incompatibilities referenced.
- https://github.com/dabl/dabl/pull/346
- https://github.com/dabl/dabl/pull/343
- https://github.com/dabl/dabl/pull/342
- https://github.com/dabl/dabl/pull/341
- Drop some now unnecessary version restrictions.
See Also: #757
Closes: #826

Upgrade required dabl version and simplify related dependency rules

---

Makefile
mlos_core/setup.py

See Also: #839
Also fixes `make dist-test` rules to workaround recently broken `pip` version interpretation when using symlinked whl files.
https://github.com/pypa/pip/issues/12911

Temporarily avoid new version of FLAML

---

.github/workflows/devcontainer.yml

Use a tagged release first, and a latest release secondarily.

Fixup to release version tagged devcontainer publishing logic

---

.devcontainer/Dockerfile
.github/workflows/devcontainer.yml

Try to add github.com ssh keys to the ssh known_hosts file to avoid prompting in scripted operations in downstream consumers.

Devcontainer tweaks

---

mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/tests/launcher_in_process_test.py
mlos_bench/mlos_bench/tests/launcher_parse_args_test.py

Convert - dashes to _ underscores when parsing CLI arg extra globals

---

mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/schedulers/base_scheduler.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/pyproject.toml

The `mlos_bench` CLI wrapper exits non-zero currently even on success.
This PR adds some basic sanity checks and makes sure we exit 0 when the process looks roughly OK.
Further work to be expanded in #523.

Basic error checks and exit zero on success

---

.github/workflows/devcontainer.yml
conda-envs/mlos-3.10.yml
conda-envs/mlos-3.11.yml
conda-envs/mlos-3.12.yml
conda-envs/mlos-3.8.yml
conda-envs/mlos-3.9.yml
conda-envs/mlos-windows.yml
conda-envs/mlos.yml

The [`build`](https://anaconda.org/conda-forge/build) name in conda-forge apparently hasn't been updated in 3 years.
Whereas [`python-build`](https://anaconda.org/conda-forge/python-build) is updated frequently.
Probably this is for namespacing reasons.

Fixup: use corrected python build package name from conda forge

---

.vscode/settings.json
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/services/remote/azure/azure_auth.py
mlos_bench/mlos_bench/services/remote/ssh/ssh_fileshare.py
mlos_bench/mlos_bench/services/types/config_loader_type.py
mlos_bench/mlos_bench/tests/conftest.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_network_services_test.py
mlos_bench/mlos_bench/tests/services/remote/azure/azure_vm_services_test.py

Minor adjustments to both display in vscode and quiet some pylint warnings.
Note: in the future I'd like to get some changes from #330 incorporated to allow more self-contained config examples, with relative paths support, added, which means changing a pile of APIs, in which case we can probably make all of these require named position values and remove those exceptions.

Tweaks for some pylint warnings

---

mlos_bench/mlos_bench/config/schemas/tunables/tunable-values-schema.json
mlos_bench/mlos_bench/tests/config/schemas/tunable-values/test-cases/good/full/bare-tunable-values-with-schema.jsonc
mlos_bench/mlos_bench/tests/config/schemas/tunable-values/test-cases/good/full/empty-tunable-values-with-schema.jsonc
mlos_bench/mlos_bench/tests/config/schemas/tunable-values/test-cases/good/partial/empty-tunable-values-without-schema.jsonc
mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
mlos_bench/mlos_bench/tunables/tunable_groups.py

Allows an empty dictionary (object) to represent the default tunable values for tunable params.
---
This should make it easier to maintain configs that loop over a chosen set of tunable values, where some of the tunable values are the default values without needing to copy/paste those values from the tunable params definitions.
- See Also: [discussion in #855](https://github.com/microsoft/MLOS/pull/855#discussion_r1786896189)
---
---
Extends existing testing infrastructure to check that this works.
---

Allow empty tunable values to represent the defaults

---

Makefile
doc/source/conf.py
mlos_core/mlos_core/tests/spaces/spaces_test.py
mlos_core/setup.py

Quick fixups to the documentation build.
---
- Expands one of the ignored warnings.
- Reformats the sphinx conf for black and pylint.
- Removes a warning from that file around redefinition of `html_theme_path`.
- Adds a dependency requirement tweak for `pyparsing` when installing under python 3.8 (unrelated other CI bug).
- Adds a workaround to a mypy false positive with in checking `np.e` as a "deleted variable" (e.g., `e` is used in a try/except block)
---
- 🛠️ Bug fix
---
- Ran `make doc` and `make check-doc`.
- Ran `make notebook-exec-test`.
---
This is a quick fix to get the CI pipeline working again.
The more complete fix to remove warning ignores from doc generation, improve cross reference linking, etc. will be handled later in #869 
---

Various quick CI fixups

---

.devcontainer/Dockerfile
.devcontainer/build/build-devcontainer-cli.ps1
.devcontainer/build/build-devcontainer-cli.sh
.devcontainer/build/build-devcontainer.ps1
.devcontainer/build/build-devcontainer.sh
.devcontainer/common.sh
.devcontainer/docker-compose.yml
.devcontainer/scripts/prep-container-build
.devcontainer/scripts/prep-container-build.ps1
.devcontainer/scripts/run-devcontainer.sh
.vscode/extensions.json
Makefile

Fixups to the devcontainer build for macOS clients.
---
- Use a more portalable random number generator
- Address some differences in docker.sock privileges.
- Address differences in `stat` arguments.
- Switch to wget mode for conda installation to workaround lack of arm64 apt repo.
- When pulling base images to prime cache, use the appropriate architecture (for Windows we only support amd64 for now).
- Remove `:latest` from `cache-from` args for `podman` compliance.
- Address some differences in `sed` syntax.
- Fixes #873 
---
- 🛠️ Bug fix
---
- local MacBook testing
- CI testing for Linux
---
Doesn't currently do builds for arm64 platform in the pipeline.
Can work towards addressing that in the future.

devcontainer build fixups for macOS clients

---

.github/workflows/devcontainer.yml
.github/workflows/linux.yml
conda-envs/mlos-3.13.yml

Add support for Python 3.13 and mark is as the expected default.
---
Upstream changed the default version of python, so this addresses changes in checks in the pipelines.
So far it seems to "just work (tm)"
---
- 🛠️ Bug fix
- 🧪 Tests
---
Usual CI tests.
---

Add support for Python 3.13 and mark is as the expected default

---

mlos_bench/mlos_bench/tests/config/cli/test-cli-local-env-bench.jsonc
mlos_bench/mlos_bench/tests/config/cli/test-cli-local-env-opt.jsonc
mlos_bench/mlos_bench/tests/config/cli/test-cli-local-env.jsonc
mlos_bench/mlos_bench/tests/config/environments/local/scripts/bench_run.py
mlos_bench/mlos_bench/tests/config/environments/local/scripts/bench_setup.py
mlos_bench/mlos_bench/tests/config/environments/local/test_local-tunables.jsonc
mlos_bench/mlos_bench/tests/config/environments/local/test_local_env.jsonc
mlos_bench/mlos_bench/tests/config/experiments/experiment_test_local.jsonc
mlos_bench/mlos_bench/tests/config/tunable-values/tunable-values-local.jsonc
mlos_bench/mlos_bench/tests/launcher_in_process_test.py

A test configuration for the environment based on local shell scripts
---
This is a sample MLOS configuration (CLI config, tunables, environment, and the scripts) that launches a local environment and invokes local shell scripts to set it up and run trials.
---
This is purely a config-based update. We might add unit tests around that setup later.
- 🧪 Tests
---
Unit tests that validate the environment and run test experiments are included in this PR.
To test the environment manually, run:
```bash
mlos_bench \
--config mlos_bench/mlos_bench/tests/config/cli/test-cli-local-env-bench.jsonc \
--globals experiment_test_local.jsonc \
--tunable_values tunable-values/tunable-values-local.jsonc
```
---
This setup is supposed to serve as an example of other …

A test configuration for the environment based on local shell scripts

---

README.md
doc/source/index.rst

Fixup broken markdown links after #869 
---
After #869 was merged the published documentation links changed which meant that future Markdown lint checks failed.
This PR fixes that. 
---
- 🛠️ Bug fix
---

Fixup broken markdown links

---

mlos_bench/mlos_bench/config/__init__.py
mlos_bench/mlos_bench/environments/__init__.py
mlos_bench/mlos_bench/environments/base_environment.py
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/services/types/config_loader_type.py
mlos_bench/mlos_bench/storage/__init__.py
mlos_bench/mlos_bench/storage/base_experiment_data.py
mlos_bench/mlos_bench/storage/base_trial_data.py
mlos_bench/mlos_bench/storage/base_tunable_config_data.py
mlos_bench/mlos_bench/storage/base_tunable_config_trial_group_data.py
mlos_bench/mlos_bench/storage/sql/__init__.py
mlos_bench/mlos_bench/storage/storage_factory.py
mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
mlos_bench/mlos_bench/tests/services/config_persistence_test.py
mlos_bench/mlos_bench/tunables/__init__.py
mlos_bench/mlos_bench/tunables/tunable.py
mlos_bench/mlos_bench/tunables/tunable_groups.py
mlos_core/mlos_core/spaces/__init__.py
mlos_core/mlos_core/spaces/converters/__init__.py

Allow loading configs from JSON strings not just files and add docs for Tunables to demonstrate and test it.
---
Adds basic support for loading a JSON config string directly.
The main purpose is to be able to show examples in docstrings that are testable (so that they don't become stale examples).
- Closes #881 
---
- 🧪 Tests
---
---
Split out from #887 
---

Allow loading configs from JSON strings and test with new docstrings for tunables

---

conftest.py
mlos_bench/mlos_bench/storage/__init__.py

Make inline unit tests that display Pandas DataFrame work in all environments, regardless of terminal width.
---
Inline tests in docstrings sometimes fail if the terminal width does not match the expected one and the pandas DataFrame got displayed differently.
- **Issue link**: Closes #895 
---
- 🛠️ Bug fix
- 🧪 Tests
---
Unit tests should pass now
---

make docstring test work in all environments

---

Makefile
doc/nginx-default.conf
doc/source/index.rst
mlos_bench/mlos_bench/__init__.py
mlos_bench/mlos_bench/config/__init__.py
mlos_bench/mlos_bench/environments/__init__.py
mlos_bench/mlos_bench/run.py
mlos_bench/mlos_bench/tunables/tunable.py
mlos_core/mlos_core/__init__.py

Doc linklint fixups
---
GithubPages serves our docs out of a `/MLOS` path, but previously we checked things out of `/` using an Nginx docker container.
This PR changes the Nginx docker container used for testing to also serve paths out of `/MLOS` and fixes the broken links found from that.
- See #891 
---
---
- Existing CI (which includes docstring and some link lint checks)
---

Doc linklint fixups

---

mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py

---
Fixes #898 by moving import away from top-level.
---
- 🛠️ Bug fix
---
Ran existing `mlos_core` unit tests, and manually tested in a fresh python env without optional deps installed.
---

Fix storage API having SMAC as a required dependency

---

.pre-commit-config.yaml

When doing partial `pre-commit run` on staged changes, only run `licenceheaders` on the changed files, not all of them.

speed improvement on licenseheaders pre-commit partial files run

---

.pre-commit-config.yaml
mlos_bench/mlos_bench/tests/storage/sql/fixtures.py

Enable pre-commit autoupdate PRs
---
Adds configs for pre-commit.ci to use to scan our repo and automatically submit PRs to update pre-commit hook version monthly.
---
---
This also enables autofix PRs to hopefully improve the turnaround time on PR reviews by automatically applying formatting fixups to a PR.
This could get confusing or annoying if PR authors don't locally pull after fixes are applied or if the formatters do something drastic that we aren't anticipating, so we may consider to disable this in the future as well.
---

Enable pre-commit autoupdate PRs

---

mlos_bench/mlos_bench/optimizers/__init__.py
mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/partial/grid_search_opt_minimal.jsonc
mlos_bench/mlos_bench/tests/config/schemas/optimizers/test_optimizer_schemas.py

Fixups for running pytest via VSCode
@motus noticed that running all tests in VSCode was hanging inside a DevContainer on MacOS.
After some debugging I determined that there was some mismatch between discovering tests and running them, specifically for the GridSearchOptimizer.  This was true on the CLI as well.
Adding it to the `__init__.py` for that submodule seems to fix the issue.
- 🛠️ Bug fix
- Local VSCode in both DevContainer and MacOS native mode.
Don't know of others like this but I wonder if that's an …

Fixups for running pytest via VSCode

---

mlos_core/setup.py

Temporarily workaround issues with LlamaTune and numpy>=2.0
LlamaTune has issues with numpy>=2.0 reporting errors like the following:
```
FAILED mlos_core/mlos_core/tests/spaces/adapters/llamatune_test.py::test_num_low_dims[2-param_space_kwargs1] - ValueError: Configuration(values={
'int_0': 245,
'int_1': 10,
'int_2': 54,
})
The above configuration was not suggested by the optimizer. Approximate reverse mapping is currently disabled; thus *only* configurations suggested previously by the optimizer can be registered.
```
- See Also: #935 
- 🛠️ Bug fix
- CI …

Temporarily workaround llamatune issues with numpy>=2.0

---

mlos_bench/mlos_bench/optimizers/__init__.py
mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py

mlos_bench.optimizers doc fixups from #912
A few changes to wording, layout, cross referencing from the docs written in #912.

mlos_bench.optimizers doc fixups from #912

---

mlos_core/mlos_core/spaces/adapters/llamatune.py
mlos_core/setup.py
mlos_viz/mlos_viz/base.py

This PR addresses a breaking change in NumPy's [universal function](https://numpy.org/doc/stable/reference/ufuncs.html) (ufunc) behavior in version 2.0, specifically affecting `np.clip` in the LlamaTune adapter code.
**Key Changes**:
- Resolves an issue where configuration retrieval fails due to type casting differences
- Explicitly casts `np.clip` output from NumPy data type (e.g., `int64`) to native Python type (e.g., `int`)
**Problem Context:**
In NumPy 2.0+, when ufuncs receive Python scalars as input, the output is [no longer](https://numpy.org/doc/stable/reference/generated/numpy.can_cast.html#numpy.can_cast) automatically cast to Python scalars. This prevents retrieving previously suggested configurations stored in `self._suggested_configs` dict during `self.inverse_transform` …

Fix dtype casting issue with numpy in LlamaTune adapter

---

mlos_bench/mlos_bench/services/remote/azure/azure_deployment_services.py

This fixes a small issue where Azure ARM requests could intermittently fail if the corresponding control plane is too busy.
This manifests as a HTTP 503 response code, with a message like:
```
ERROR Response: <Response [503]> :: {"error":{"code":"ServerTimeout","message":"The request timed out. Diagnostic information: timestamp '20250209T125446Z', subscription id '...', tracking id '...', request correlation id '...'."}}
```
According to the official docs, these responses indicate the request should be retried: https://learn.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes
- 🛠️ Bug fix …

Azure retry on result timeout / server busy

---

doc/requirements.txt
doc/source/conf.py
mlos_bench/mlos_bench/tunables/tunable_types.py

Fixups for recent changes in sphinx dependencies
- Changes the type resolution for a few type aliases from `data` to `type`
- Excludes flaml's `Domain` type from resolution.
- Excludes `Future` from resolution nitpick (similar error to `Ellipsis`)
- Documents the new versions that caused these.
- 🛠️ Bug fix

Fixups for recent changes in sphinx dependencies

---

mlos_bench/mlos_bench/launcher.py

Fixing an args type bug in launcher tunable_values processing
If tunable_values are specified in both a config file and on the cli args, but the config file specifies them as a string, python will throw an exception when trying to concat a string and a list.  The json schema allows either a list of paths or a single path, so this is valid in that sense.
This also fixes the processing function args to only accept a list in both cases.
- 🛠️ Bug fix
Locally

Fixing an args type bug in launcher tunable_values processing

---

mlos_bench/mlos_bench/services/local/local_exec.py
mlos_bench/mlos_bench/tests/services/local/local_exec_test.py

Copy local environment variables and explicitly pass them to the child process.
When we explicitly provide the environment variables to pass to the `subprocess.run()` call, only those variables get passed to the child process. That prevents the child process from seeing the environment variables of the parent MLOS process. We've fixed that issue for MLOS on Windows but not for other systems. This PR fixes it for Linux and MacOS.
- 🛠️ Bug fix
- 🧪 Tests
Update the existing unit tests to check for MLOS parameters *and* parent environment variables being passed to the child process.

bugfix: local env not passed to the child process when shell_env_params present

---

Makefile
mlos_bench/mlos_bench/config/__init__.py
mlos_bench/mlos_bench/config/environments/network/virtual-network-environment.jsonc
mlos_bench/mlos_bench/config/tunables/dummy-tunables.jsonc
mlos_bench/mlos_bench/environments/__init__.py
mlos_bench/mlos_bench/environments/remote/remote_env.py
mlos_bench/mlos_bench/launcher.py
mlos_bench/mlos_bench/services/config_persistence.py
mlos_bench/mlos_bench/tunables/__init__.py

Document the Environment Parameterization and Variable Propagation.
Update the docstrings in `mlos_bench.environments` module to include information on Environment Parameterization and Variable Propagation.

Document the Environment Parameterization and Variable Propagation

---

mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/experiment.py
mlos_bench/mlos_bench/storage/sql/trial.py
mlos_bench/mlos_bench/tests/storage/trial_schedule_test.py

Bug fix: restore trial_runner_id on reload from Storage
@jsfreischuetz noticed that `pending_trials` was returning `Trial` objects without a `trial_runner_id` even though they were previously set.
This change fixes that and closes #968.
- Requires explicit `trial_runner_id` on `Trial` object instantiation
- Adds it in places where it was missing.
- 🛠️ Bug fix
- 🧪 Tests
New and existing tests.
Found in the course of work on #967

Bug fix: restore trial_runner_id on reload from Storage

---

.github/instructions/README.md
.github/instructions/bash.instructions.md
.github/instructions/default.instructions.md
.github/instructions/json.instructions.md
.github/instructions/markdown.instructions.md
.github/instructions/python.instructions.md
.github/instructions/rst.instructions.md
.github/prompts/README.md
.github/prompts/TODO.md
.github/prompts/add-config-examples-to-module-docstring.prompt.md
.github/prompts/add-sphinx-crossref-to-docstrings.prompt.md
.github/prompts/split-large-change-branch-to-separate-change-branches.prompt.md
.vscode/settings.json
CONTRIBUTING.md

Adding some VSCode Copilot integrations.
- Adds custom `.instructions.md` Copilot chat prompt context to help in editing and reviewing in VSCode.
- Adds custom `.prompt.md` Copilot chat prompt instructions for performing certain common tasks.
- Adds a `TODO.md` for notes on additiona custom prompts to develop later.
See Also: <https://code.visualstudio.com/docs/copilot/copilot-customization>
- Disables two annoying VSCode editor features:
1. Stop automatically removing "unused" imports.
2. Stop asking to configure via `make`
Interactive VSCode coding. …

Adding VSCode Copilot integrations

---

.vscode/settings.json
mlos_bench/mlos_bench/schedulers/base_scheduler.py
mlos_bench/mlos_bench/schedulers/sync_scheduler.py
mlos_bench/mlos_bench/schedulers/trial_runner.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/experiment.py
mlos_bench/mlos_bench/tests/storage/trial_schedule_test.py

Rename and reorganize some Scheduler methods
In preparation for ParallelScheduler PR (#971) this PR
1. Renames a few methods for clarity (e.g., `schedule_trial` --> `add_trial_to_queue`) so that the role of other methods (e.g., `assign_trial_runners`) is more clear and readily overridable.
2. Moves some methods to the base class.
This is done based on an observation that some of the methods (e.g., the main `start` loop) are largely reusable across both SyncScheduler and ParallelScheduler if the method separation is done a little bit more fine grained such that each can override the only the parts they need to.
Additionall, it also
1. Also adds a subtle tweak on the `pending_trials` method in order to filter based on …

Rename and reorganize some Scheduler methods

---

.vscode/settings.json
mlos_bench/mlos_bench/environments/status.py
mlos_bench/mlos_bench/storage/base_storage.py
mlos_bench/mlos_bench/storage/sql/common.py
mlos_bench/mlos_bench/storage/sql/experiment.py
mlos_bench/mlos_bench/storage/sql/storage.py
mlos_bench/mlos_bench/storage/sql/trial.py
mlos_bench/mlos_bench/tests/storage/test_storage_pickling.py

Make Storage objects picklable and resumable by mp.Pool workers.
To support a `ParallelTrialScheduler` with `Trials` running thru `TrialRunners` in separate processes using `multiprocessing.Pool` we need to be able to "send" all necessary state to "blank" python processes using pickle since python doesn't actually use a `fork` strategy for multiprocessing.
This change enables that by doing the following:
1. Allow pickling the core `Storage` class by hooking `__getstate__` and `__setstate__` to disconnect the `Engine` prior to pickling and reconnect on unpickling (restore).
2. Allow recreating an `Experiment` and `Trial` object by fetching it from the `Storage` by `experiment_id` and `trial_id` respectively.
These two …

Make Storage objects picklable and resumable by mp.Pool workers

---

.github/instructions/python.instructions.md

Improvements on copilot instructions for python docstrings
Make sure we use numpydoc format.
Improvements on #972 
- 🛠️ Bug fix
Local VSCode.

Improvements on copilot instructions for python docstrings

---

mlos_bench/mlos_bench/config/schemas/schedulers/base-scheduler-subschema.json
mlos_bench/mlos_bench/config/schemas/schedulers/scheduler-schema.json
mlos_bench/mlos_bench/config/schemas/schedulers/sync-scheduler-subschema.json

Refactor Scheduler schema definitions to make it easier to add new ones.
Simple refactor of the Scheduler schemas to allow making new ones as a copy/edit of the `synchscheduler-subschema.json`.
- 🔄 Refactor
- Exisiting CI checks for good and bad scheduler config files still pass.
- Adding additional tests to actually load those configs with `mlos_bench` next.
- Splitting some new testing infra out from #973.
- Adding `MockScheduler` next, then `ParallelScheduler` in #971. …

Refactor Scheduler schema definitions to make it easier to add new ones.
